### ISSUE TITLE
Integrate to task switcher

### ISSUE THREAD

**Issue by amenk** [OpherV/gitflow4idea#104]
We are using a task server (Redmine) in PHPStorm and open tasks using the `Tools -> Tasks and Contextes -> Open Task`. This function allows creating new branches on the fly.

Could you integrate the `git flow`, so it is possible to create a new feature or hotfix on the fly?

**Comment by OpherV** [comment]
Gitflow4idea is a GUI tool that bridges the git flow CLI.
If you're working with some sort of automation perhaps you run git flow from the command line using the same tool?

**Comment by amenk** [comment]
I am talking about the PHPStorm Task features ... all GUI ... maybe a bit less-known. https://www.jetbrains.com/phpstorm/help/managing-tasks-and-context.html

**Comment by OpherV** [comment]
I don't see how task automation is in the scope of this plugin...

In any case Gitflow4idea exposes all of its actions to the IntelliJ platform, for example to binded to shortcut keys. Maybe there's a way to bind tasks to actions? If not - then this should definitely be a feature of the IntelliJ task gui

**Comment by amenk** [comment]
No clue if IntelliJ exposes the task open functionality to plugins. Just for this VCS operations it would be nice to have Git Flow actions as well (start feature)

![screenshot](https://cloud.githubusercontent.com/assets/1087128/13255181/2ebdbe58-da45-11e5-92e9-b699736806a6.png)

**Comment by OpherV** [comment]
Well, then you should definitely suggest this to the IntelliJ team... I have no control over the GUI of the open task window...

**Comment by amenk** [comment]
I have asked their support if there's an extension point to add a function to that menu. If  that exists, I think it's still necessary to add the feature in your extension or am I wrong?

**Comment by dmitry-avdeev** [comment]
Hi, we have pull request for extending Open/Close Task dialogs. Most likely it will be pulled into IDEA 16 or following updates.

**Comment by OpherV** [comment]
@dmitry-avdeev @amenk That's neat! Keep me posted for when this happens and I'll see how to go about integration

**Comment by dmitry-avdeev** [comment]
"Pluggable open/close task dialogs" is committed: f7a02a6ee8e6228bebfc7699c30ec76a27a2dd55.

**Comment by kevincam3** [comment]
OpherV,

Any chance this will get implemented? I see there's an API to be able to do it now.

**Comment by OpherV** [comment]
@kevincam3  Of course there's a chance! It's only a function of time :)

**Comment by littlethoughts** [comment]
Just mentioning that I would be interested in this too, it's not only @amenk and @kevincam3 👍

**Comment by tiger-tw** [comment]
I would like to see this feature too

**Comment by MLoenhardt** [comment]
+1
I would like to use this feature. Would be a great relief in our daily work.

**Comment by OpherV** [comment]
Already started looking into it! Hoping to get this implemented soon

**Comment by OpherV** [comment]
@amenk @kevincam3  @littlethoughts @tiger-tw  @MLoenhardt 
Just done implementing this, should now be available in 0.4.9
Please test and thanks for the patience

**Comment by kevincam3** [comment]
Something confusing to me.

I've attached a screenshot. From what I see. I don't know if a branch is going to be created from the develop or from the master. Please advise.

![git-flow-branch](https://cloud.githubusercontent.com/assets/870934/17738349/3dea5362-6467-11e6-8de0-60f456da4189.jpg)

**Comment by OpherV** [comment]
@kevincam3 The open task integration interface allows me to add a panel in the existing "open task" panel, but not change its original content. So what you see here is both the original panel content under "VCS operations" and the new gitflow functionality under "Gitflow operations". 

What would happen if you tick both options? 
My guess - it will create two separate branches. One called `MIN-18` and one called `hotfix/MIN-18`
My suggestions - if you want to use gitflow, untick "create branch" under VCS operations and choose the desired action under Gitflow operations. 

It's not super-elegant UX wise, but it's better than nothing :)

**Comment by kevincam3** [comment]
Any chance that you can make it so that when I click on a radio under the Gitflow operations that it will uncheck Create branch and Use branch under the VCS operations?

**Comment by OpherV** [comment]
Unfortunately no... I have no access to the VCS operations panel at all. @dmitry-avdeev ideas how to tackle this?

**Comment by kevincam3** [comment]
I choose 'master' as the base but I got this message:

![2016-08-17_16-05-18](https://cloud.githubusercontent.com/assets/870934/17749695/4a42ac6c-6495-11e6-98f3-4b5694b782ca.jpg)

**Comment by kevincam3** [comment]
After closing an active task it said it merged to master and develop, but it only merged to develop
