### ISSUE TITLE
Please support IntelliJ IDEA 2016.2 EAP (162.74.16)

### ISSUE THREAD

**Issue by natros** [OpherV/gitflow4idea#111]
IntelliJ IDEA 2016.2 EAP
Build #IU-162.74.16, built on May 13, 2016
IntelliJ IDEA EAP User
Expiration date: June 12, 2016
JRE: 1.8.0_92-b14 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Thank you.

**Comment by RichWeber** [comment]
+1

**Comment by tmartensen** [comment]
Now up to build #IU-162.1024.1.

**Comment by throrin19** [comment]
+1

**Comment by fbudassi** [comment]
+1

**Comment by Xplouder** [comment]
Edit **until-build="175.999999"** on **/META-INF/plugin.xml** file inside the .jar file and save.
Working here so far.

Or just download here: [gitflow-plugin-updated.zip](https://github.com/OpherV/gitflow4idea/files/362870/gitflow-plugin-updated.zip)

**Comment by aligarden** [comment]
+1
@Xplouder   your file doesn't work for me

**Comment by OpherV** [comment]
I'm on this! Sorry for the delay everyone I was abroad

**Comment by kernkonzentrat** [comment]
@OpherV ...thanks mate

**Comment by martincollar** [comment]
Hello. I have PhpStorm 2016.2
Build #PS-162.1121.38, built on July 12, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I'm getting error with version 0.4.8. PhpStorm won't open project at all I'm only able to disable plugin again.
![screen shot 2016-07-19 at 13 56 16](https://cloud.githubusercontent.com/assets/3909724/16949033/9d4fe260-4db8-11e6-84ca-997b8d0a98b4.png)

@OpherV can you please help me? Thanks

**Comment by OpherV** [comment]
@martincollar Does this happen for every project? For new ones as well?
Can you paste the full stack trace?

**Comment by martincollar** [comment]
@OpherV Im not able to create new project or open existing if this plugin is enabled... 
Can you please help me how to find it? Im on Mac..
![screen shot 2016-07-19 at 15 20 272222](https://cloud.githubusercontent.com/assets/3909724/16951398/15d4032c-4dc5-11e6-8e12-82f93e11c90b.png)

**Comment by martincollar** [comment]
Here is log from point of enabling plugin and restart.. Than app stops on Welcome screen  where is selection of project instead of opening last one..
[log.txt](https://github.com/OpherV/gitflow4idea/files/371567/log.txt)

Here is log from point when i tried to Open some files from Welcome screen 
[log2.txt](https://github.com/OpherV/gitflow4idea/files/371577/log2.txt)

**Comment by martincollar** [comment]
is there any chance that this will be resolved? Reinstall with local data removal didnt help.

**Comment by OpherV** [comment]
@martincollar I took another look at your logs but I'm afraid I have no idea why your installation of Idea will not load the plugin. Googling around makes me suspect something about the Java version Idea runs on - but it might not be the case. Can you try to open an Issue for Jetbrains support and give me the URL? Maybe with their assistance we can figure this out and solve it for you...
