### ISSUE TITLE
Add publish and pull action

### ISSUE THREAD

**Issue by famaridon** [OpherV/gitflow4idea#118]
Hi,

can you add pubilsh and pull on feature and hotfix ?

**Comment by OpherV** [comment]
These already exist. You need to be on the feature or hotfix branch for them to appear in the Gitflow menu

**Comment by famaridon** [comment]
I'm on feature but I don't have it

![gitflow feature publish](https://cloud.githubusercontent.com/assets/7051149/17942161/8c82a874-6a36-11e6-93d9-68824efcf758.jpg)

Intellij 2016.2.2
GitFlowIntegration 0.4.9

It's a bug ?

**Comment by OpherV** [comment]
@famaridon your feature is probably already published (a branch with the same name exists on your remote).  That's why you don't see the option in the menu.

**Comment by famaridon** [comment]
Ok yes it's already publishes.

Sry this plugin is just perfect :)
