### ISSUE TITLE
Wrong message when finishing a release

### ISSUE THREAD

**Issue by natros** [OpherV/gitflow4idea#123]
After finished a release, the popup balloon shows that branch 'feature/1.4.0' was merged instead of release/1.4.0

Event log:

```
14:58   Checked out release/1.4.0 (show balloon)
15:27   2 files committed: update version to 1.4.0
15:27   1.4.0: The release branch 'feature/1.4.0' was merged into 'develop' and 'master'
```

IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
Licensed to Filipe Sousa
Subscription is active until November 4, 2016
For educational use only.
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

git flow version: 1.10.2 (AVH Edition)

**Comment by OpherV** [comment]
Can you provide steps to reproduce?

**Comment by natros** [comment]
![demo](https://cloud.githubusercontent.com/assets/4996289/21007540/3d461636-bd35-11e6-86cb-32f3b0f35d35.gif)

**Comment by natros** [comment]
[fsousa@imac ~]$ git flow version
1.10.2 (AVH Edition)
