### ISSUE TITLE
Switch to appropriate feature branch when active task was changed

### ISSUE THREAD

**Issue by drupality** [OpherV/gitflow4idea#124]
I am creating a feature branch when I selected task from available task list. It is awesome that I'm able to do it inside new task dialog. However if I switch to another task, I have always old branch active. I would like to switch to branch related to current task if exists.

**Comment by YanickFrehner** [comment]
Is there a way to implement this?
I would very appreciate this enhancement!
If i can, i would also try to implement this myself if you give me a hint where to look at

**Comment by OpherV** [comment]
@YanickFrehner I would try to find the IntelliJ specific api for the task list and see if there's an event or a hook that you can use which happens after a task switch... A good starting point would be http://www.jetbrains.org/intellij/sdk/docs/welcome.html

After you find something like that, implementing the required Gitflow4idea part should be fairly straightforward :)
