### ISSUE TITLE
Git now has GitFlow in it, but not fully compatible with this plugin

### ISSUE THREAD

**Issue by zorner** [OpherV/gitflow4idea#125]
The hiccup I have run into is getting gitflow init to work: 

14:12:09.561: git -c core.quotepath=false flow init
Which branch should be used for bringing forth production releases?
   - 1.2.34
   - 1.2.43
   - 1.2.45
   - 1.2.50
   - JKS_exertalized
   - master
14:12:19.180: master
' does not exist.
Branch name for production releases: [master]

Manually running the command on the command line works, as you can input the correct names.

**Comment by OpherV** [comment]
What do do you mean by "Git now has GitFlow in it"?

**Comment by zorner** [comment]
As of Git 2.6.4, Git now has GitFlow included in the package/download. You no longer have to get something that implements GitFlow on top of Git.

**Comment by kevicsalazar** [comment]
Same error, I supposed that is necessary to check this library if still working

**Comment by OpherV** [comment]
I don't see any mention of this in the Git release notes for 2.6.4
https://github.com/git/git/blob/master/Documentation/RelNotes/2.6.4.txt

Do you know which model of git flow did they include? The original NVIE one? The Avogler one?

**Comment by emcek** [comment]
It is included in windows version of Git: https://github.com/nvie/gitflow/wiki/Windows
```
gtqk84@CNU24691MP MINGW64 ~
$ git --version
git version 2.10.0.windows.1

gtqk84@CNU24691MP MINGW64 ~
$ git flow version
1.9.1 (AVH Edition)
```

**Comment by zorner** [comment]
Same git flow version:

C:\>git --version
git version 2.8.3.windows.1

C:\>git flow version
1.9.1 (AVH Edition)

**Comment by OpherV** [comment]
@emcek @zorner thanks for the logs. the bug is probably just a parsing issue. I'll look into it

**Comment by OpherV** [comment]
Just committed a solution for this, the next version would have it

**Comment by OpherV** [comment]
Fixed in 0.6.1

**Comment by Naion** [comment]
Hi I am using the linux version 0.6.6 and when I try to use the dropdown on the right lower corner this apear in the git console.

git -c core.quotepath=false flow init
Which branch should be used for bringing forth production releases?
   - master
   - develop

I used the same command in the terminal so I can choose the branch, after setting them it worked.

**Comment by OpherV** [comment]
@Naion this sounds like #198 , and isn't related to this closed bug. 

Please provide which intellij version, os version and gitflow version are you using (over at the proper bug thread)
