### ISSUE TITLE
Not compatible with Intellij IDEA 2016.3

### ISSUE THREAD

**Issue by SUPERCILEX** [OpherV/gitflow4idea#127]
The first RC for 2016.3 just came out and I still can't install this plugin. Intellij keeps saying that it's incompatible with 2016.3.

**Comment by ctaepper** [comment]
it's not working in 2016.3 final version either. can you please fix that?

**Comment by SUPERCILEX** [comment]
@OpherV any idea when a new release is coming out?

**Comment by OpherV** [comment]
@SUPERCILEX  Soon. I'm testing this with a few other bugs I'm tackling, then it'll be released

**Comment by SUPERCILEX** [comment]
@OpherV Sounds good!

**Comment by trycoon** [comment]
Second that. :-)

**Comment by OpherV** [comment]
New version released
