### ISSUE TITLE
Git Flow plugin for Idea build 171 (2017.1 EAP)

### ISSUE THREAD

**Issue by costalfy** [OpherV/gitflow4idea#132]
Hi,
I would like to install Git Flow plugin for Idea 2017.1 EAP (build 171.2455.10) but i can't see it in Jetbrain repository plugins
![2017-01-24 09_49_26-browse repositories](https://cloud.githubusercontent.com/assets/1092544/22240239/74174eb4-e21a-11e6-8412-dae3a8e3ec5a.png)

**Comment by OpherV** [comment]
The EAP compatible version will be available soon

**Comment by throrin19** [comment]
Any news ?

**Comment by OpherV** [comment]
I apologize for the delay - Swamped at work. Won't be long now - thanks for understanding

**Comment by throrin19** [comment]
The 2017.1 is released. Any news ?

**Comment by OpherV** [comment]
Should be up in the repository momentarily. Thank you for your patience.
