### ISSUE TITLE
Git Flow for Rider

### ISSUE THREAD

**Issue by mrvsoft** [OpherV/gitflow4idea#134]
Plugin 'Git Flow Integration' is incompatible with Rider

**Comment by OpherV** [comment]
Can you please post a screenshot of your Rider 'about' screen?

**Comment by mrvsoft** [comment]
Hi. I won't be able to send you a screen version in which the error
occurred, because it is no longer available. But I locally fixed this
troubles by changing the version from 162 to 145 in the line "idea-version
since-build" in file plugin.xml of plugin.

2017-03-20 22:15 GMT+04:00 Opher Vishnia <notifications@github.com>:
