### ISSUE TITLE
Grant role to other people for merging Pull request and publish to intellij plugins repository

### ISSUE THREAD

**Issue by costalfy** [OpherV/gitflow4idea#135]
Hi,
don't you thinks it's time to grant role to any other people you like for validating  pull request and publish on intellij plugins repository web site?
Regards

**Comment by OpherV** [comment]
There are no other developers working on this project actively but me. I wish there were, but so far I'm the only one doing any bug fixing based on user input. Sometimes I get the occasional PR which I happily merge, but that's about it.

If you'd like to step up as co-maintainer - I warmly welcome you to start contributing. There's a full list of open issues and enhancement suggestions [here](https://github.com/OpherV/gitflow4idea/issues). That would be a great way to start.
