### ISSUE TITLE
Invalid file when I try to install the plugin

### ISSUE THREAD

**Issue by soyFerrero** [OpherV/gitflow4idea#145]
When i try to install in Webstorm 2017.2 >>> Invalid File: The 'gitflow4idea_0.5.1.jar' contains no settings to import. Please make sure you have generated the file using 'File|Export Settings' feature.

**Comment by OpherV** [comment]
@soyFerrero does the same thing happen when you try to install it from the jetbrains repo?

**Comment by soyFerrero** [comment]
I can not see it.  
When I try to look for it in the Browser >>> " nothing to show"

**Comment by OpherV** [comment]
Can you please paste the version + build number for your Webstorm?

**Comment by soyFerrero** [comment]
WebStorm 2017.2 EAP
Build #WS-172.2465.2, built on May 23, 2017
WebStorm EAP User
Expiration date: June 22, 2017
JRE: 1.8.0_152-release-855-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by OpherV** [comment]
That's the reason why you don't see it in the JetBrains repo, I haven't released 172 support yet.
You tried to manually install an incompatible version.
A new version will be available soon

Closing as a dup of #142
