### ISSUE TITLE
GitFlow re-initializes status bar menu when finishing hotfixes or checking out new branches

### ISSUE THREAD

**Issue by johnboulder** [OpherV/gitflow4idea#146]
I use IDEA and GitFlow frequently every day, and by the end of the day after finishing a number of hotfixes or features my status bar will usually end up looking like the picture below.

![image](https://user-images.githubusercontent.com/9061140/27092232-45c91192-5028-11e7-8ee2-6c1ef851467a.png)

I'm using Intellij IU.171.442.56 on Ubuntu 16.04 in a development environment with 2 VCS roots.

**Comment by OpherV** [comment]
Wow that's such a neat bug! :)
When does it happen that another status bar widget gets added?

**Comment by johnboulder** [comment]
I've noticed it seems to happen primarily when I push changes on a branch, and then only once after a push when I switch branches. It occasionally seems to happen when checking out a new branch. 

It's important to note that I recently switched from a 2016 build of IDEA, and this only started happening in the 2017 build.
