### ISSUE TITLE
Starting a release does always tell the branch is already checked out

### ISSUE THREAD

**Issue by lubberscorrado** [OpherV/gitflow4idea#151]
No matter what text i enter for a planned release name when selecting "Start Release", the dialogue always tells me i already have checked out that branch, which is not true. Thus i cannot create a release, because the OK Button is disabled.

![image](https://user-images.githubusercontent.com/2172082/27435857-b2a6e870-575d-11e7-8244-e85fe6e40c53.png)

I used PHPStorm 2017.1 aswell as 2017.2 EAP, same issue

This only happens for the latest 0.6.1 release

**Comment by OpherV** [comment]
Very strange. I did a huge refactor in the last version so some bugs are bound to pop up...
 Do you have multiple repos in this project? What do your branches look like?

**Comment by OpherV** [comment]
Nevermind - I can reproduce. On it!
