### ISSUE TITLE
Should there be a pull option?

### ISSUE THREAD

**Issue by jurgenhaas** [OpherV/gitflow4idea#152]
First of all, this is one of the most time saving plugins in my workflow, I'm so greatful for it. Thanks so much.

We do work with a default git flow workflow and a number of remote working developers are allowed to create new releases, which happens several times a day. The "problem" then is that such a developer first has to checkout master and develop, fetch and pull that and then finish the new release. If they don't, the error is that the new release can't be merged with the local master as that has diverged from the orgin master.

In the options for this plugin, there we have selected to automatically fetch from origin, but that still leaves the local master being diverged from the origin master. My thinking was that similar to the fetch option, if there was a pull option, this would be avoided. Or am I doing something wrong?

**Comment by OpherV** [comment]
gitflow4idea is just a a front for the CLI tool, so if options exists in the CLI I can definitely add it in the GUI
Is this something that can be done with the gitflow command line? and if so how?

**Comment by jurgenhaas** [comment]
Good point, don't think there is such an option. So I wonder how others are doing this. Probably, what should work in theory is to no have a local master branch, as that's certainly not required in this workflow. Then it can't civerge from the origin one. Just don't know if git flow can merge directly into the remote master, I certainly doubt that.

Maybe my question is then better placed somewhere in the gitflow community.

**Comment by OpherV** [comment]
Closing for now - but I'll reopen if you find a way to achieve this with the CLI

**Comment by jurgenhaas** [comment]
It looks like this is a topic for others as well, see https://github.com/petervanderdoes/gitflow-avh/issues/235

There is going to be a cli option for this, it just seems that it's not finally decided what's that going to be called.
