### ISSUE TITLE
Cannot finish a feature

### ISSUE THREAD

**Issue by fmmarzoa** [OpherV/gitflow4idea#163]
Created a new feature successfully, but when I try to finish it nothing happens at all. Probably crashes. I see nothing related on the console, though, feel free of asking me for additional information.

IntelliJ Idea 2017.2
Git Flow Integration plugin version 0.6.2

**Comment by ciscorucinski** [comment]
I started a new release and tried to finish the release; however, I received the following issue...
```
Branches 'master' and 'origin/master' have diverged.
Fatal: And branch 'master' may be fast-forwarded.
```

... I solved the issue with github's feature request / diff tools, but I am uncertain about how to go about finishing the release. I already finished it without gitflow, but gitflow still has that option available.

I don't know if I go through the finish workflow, that it will not create a useless duplicate that I need to remove or what not.

Note: I have the same setup as @fmmarzoa

**Comment by OpherV** [comment]
@ciscorucinski that's the default behavior of git / git flow. This plugin is just a GUI front for the latter. To finish a release you need to make sure both your master and and develop branches are up to date, then run the finish feature command. 

I don't know what state you've left your git branches at if you already did your merges manually without git flow. gitflow4idea shows that option if you're on a release branch. If your develop and master branches are already merged with the release, you can simply delete the release branch.
