### ISSUE TITLE
The feature branch 'feature/3097_goBeta' was merged into 'null'

### ISSUE THREAD

**Issue by denisbondar** [OpherV/gitflow4idea#164]
Hi!

I see the message "The feature branch 'feature/3097_goBeta' was merged into 'null'" in the Event log and on the balloon after the branch merged (action: Finish Feature).
In fact, the merge is correct.

PhpStorm 2017.2.1
Windows 10

**Comment by OpherV** [comment]
Duplicate of #144 
Please provide a set of steps to reproduce this (in the other thread)
