### ISSUE TITLE
172.3 compatibility

### ISSUE THREAD

**Issue by dschulten** [OpherV/gitflow4idea#171]
I cannot install the plugin into the 2017.3 EAP. Could you please bump up the version?

**Comment by ciscorucinski** [comment]
I think @dschulten  means 173.* compatibility. I have to revert back to 172.* to get this plugin back

**Comment by dschulten** [comment]
Exactly :)

**Comment by OpherV** [comment]
Yes, as soon as I test the compatibility thoroughly
