### ISSUE TITLE
Multi Repository Support

### ISSUE THREAD

**Issue by YanickFrehner** [OpherV/gitflow4idea#175]
Please add Multi Git Repository Support like the standard Git implementation in PHPStorm already got one

**Comment by OpherV** [comment]
What do you mean? Multi repo support already exists.

**Comment by YanickFrehner** [comment]
Sorry for the Short description.
What I realy mean is that i would realy appreciate if it is possible to keep the multiple repositorys in sync, Like it is possible in normal Git implementation of PHP storm.
For example creating a new feature branch for all the repositorys in the Project with one klick, when the repositorys are already on the same branch

**Comment by OpherV** [comment]
Duplicate of #166
