### ISSUE TITLE
Git config file not written when creating new branch

### ISSUE THREAD

**Issue by carnau** [OpherV/gitflow4idea#182]
I found that everytime I was to finish a feature, the message always show that is merged into null, no matter which base branch I used. After looking into it more closely I found that when I create the feature nothing is added inside ./git/config file. Adding the proper lines makes it work like expected.

OS: macOs High Sierra 10.13.2

If there is any way to debug this issue, I will be happy to help.

**Comment by OpherV** [comment]
Gitflow4idea is a gui for the gitflow command line tool. 
Do you get the same result when you use  `git flow finish feature` from the CMD?
If so - it's not an issue with the plugin, but rather something to do with gitflow on your machine
If not - please post the output of your intellij VCS console

**Comment by carnau** [comment]
You were right, the git-flow version installed through homebrew it's not the same as the one I had installed in Linux, once I switched to the avh version everything works as expected.
