### ISSUE TITLE
[Hotfix]Error on tag

### ISSUE THREAD

**Issue by throrin19** [OpherV/gitflow4idea#19]
On Publish Hotfix, your plugin return errors in version control terminal because in your command to create tag, you add too many parameters.

```
11:11:01.427: cd /home/throrin19/Programmation/Web/goomeoeventsapi
11:11:01.427: git flow hotfix finish -m "Tagging version 4.0.9" 4.0.9
Switched to branch 'master'
Merge made by the 'recursive' strategy.
 app/controllers/v1/events_controller.js | 14 ++++++++------
 1 file changed, 8 insertions(+), 6 deletions(-)
fatal: too many params
Tagging failed. Please run finish again to retry.
```

**Comment by throrin19** [comment]
On OSX, your plugin does not works. I install gitflow with homebrew and after i try to test the `git flow` command : 

![gitflow_1](https://cloud.githubusercontent.com/assets/1394778/5701976/ae3fbfa6-9a53-11e4-8a2a-4ef3029e1339.png)

After that, I launch webstorm, phpstorm, ... with your plugin and if i try to init my repository, i have this error : 

![gitflow_2](https://cloud.githubusercontent.com/assets/1394778/5701984/c5e61c18-9a53-11e4-82a2-ed62dd49d53a.png)

**Comment by OpherV** [comment]
@throrin19 It's a known issue with OSX. Did you try all the suggestions mentioned in #7?

**Comment by throrin19** [comment]
yes, I try this : 

```
sudo ln -s /usr/local/bin/git-flow /usr/bin/git-flow
```

It works fine

**Comment by OpherV** [comment]
Glad to hear
