### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by nnar1o** [OpherV/gitflow4idea#195]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Plugin works very slow. 

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

When I click on the gitflow combo in the button bar it takes more than 10s to see the menu. The git plugin works fine.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.4
  - Gitflow version: 1.11.0 (AVH Edition)
  

  ~~~~
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
Licensed to 
Subscription is active until December 28, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Can you try the latest plugin version 0.6.5.1?

After you update - 
Does this happen on every project? 
Try opening an empty project and initializing it with git. Does that still happen then?

**Comment by nnar1o** [comment]
Thanks for answer. 

I updated the plugin to the latest version and nothing changed.

I tried to create an empty project as you suggested and there is no lag. Probably the problem is that the project I have is huge and contains many files. But why gitflow plugin freezes the Intellij window? I think it just needs to list branches what is very fast ("git branch" in my console takes no time). I asked my colleagues and they have the same lag so it is probabely not a problem with my computer/os.

Best regards

**Comment by lppedd** [comment]
@nnar1o @OpherV Looking at the source code I see there may be quite heavy method called multiple times for nothing. I need to take a look when at home. I think we can make this popup a lot more performant.

**Comment by OpherV** [comment]
@lppedd I'm interested to hear about your findings!

**Comment by OpherV** [comment]
@lppedd pinging you about this again - Which heavy methods were you referring to?

**Comment by avatarkava** [comment]
Not sure on weight of methods, but if I have a project with a large vendor/ folder (using composer to handle dependencies), it can take up to 30s for the menu to appear when clicking on the combobox, as every library is coming from a different git repository.  I assume it is taking some time on click to traverse the folder structure and pull in all of the repository information.

Aside from performance gains that could be had by possibly caching this, it doesn't appear to take into account the "ignored files" functionality of the project.  I have vendor/ ignored, which if accessible might allow the plugin to also suppress traversing into ignored folders.

**Comment by RickS-C137** [comment]
I also had perfomance issues and opened a ticket at Jetbrains. They told me the following:
"According to the dumps, the issue is caused by the gitflow plugin that executes some git command​ in the UI thread.
Please disable the GitFlow integration plugin and report the issue to the plugin author."
I've installed version 0.6.7 of the plugin, IntelliJ 2018.3.4 on MacOS 10.14.3.
I think this could be related to this issue. Do you want to have a look at the threatdumps IntelliJ created?

**Comment by avatarkava** [comment]
@RickS-C137 #216 should help it quite a bit if not fix it outright.

**Comment by OpherV** [comment]
Please test with 0.6.8
