### ISSUE TITLE
hotfix branch also needs an option -k to keep branch after performing finish

### ISSUE THREAD

**Issue by jillesmc** [OpherV/gitflow4idea#199]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
There is an option "Keep branch after performing finish [-k]" for features and releases branches, but there is no option for hotfixes. By consequence pull requests for hotfixes are closed instead of merged on github.

* **What is the expected behavior?**
Create the an option -k for hotfixes' branches and 

* **What is the motivation / use case for changing the behavior?**
Every person who uses this plugin will need to swap to console to finish hotfixes because it doesn't have an option to keep the branch after performing branch finish.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.5.1
  - Gitflow version: 1.11.0 (AVH Edition)

PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.34-1-MANJARO

**Comment by OpherV** [comment]
Luckily this is an easy feature to implement. I love those 😀 
It'll be included in the next version

**Comment by OpherV** [comment]
Will be available in 0.7.0

**Comment by OpherV** [comment]
Version 0.6.9 is now on the Jetbrains Repo
