### ISSUE TITLE
Remove until-build attribute from idea-version tag in plugin.xml 

### ISSUE THREAD

**Issue by tdegrunt** [OpherV/gitflow4idea#200]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

Remove until-build altogether from the META-INF/plugin.xml.

http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html?search=until-build

<idea-version since-build="7000" until-build="11999"/>

* **What is the current behavior?**

Currently gitflow4idea stops working on almost every new release because of this tag.

* **What is the expected behavior?**

gitflow4idea should keep working 🙂 

* **What is the motivation / use case for changing the behavior?**

I suspect you have many more tickets that it doesn't work because of this tag then you would have if you just remove the "until-build".

If in the future someone opens a ticket that is indeed doesn't work, in that case it's a real issue.

**Comment by OpherV** [comment]
In general I'm against this because from my experience,  sometimes APIs change and break between IntellIJ version,, and I don't want to give the false impressions that the plugin automatically works with every new version because it might not. 

Things break and I want to try and make sure nothing bad happens to your code/project because of these incompatibilities. That's why I go to great lengths to test every version of the plugin when I update it to new versions of IntelliJ. This does mean updates take longer (since I'm doing this for free on my free time) but that's open source for you :)

**Comment by Jeansen** [comment]
Hm, I tend to disagree. I understand, that you do this in your spare time. And I am truly grateful for all your efforts. I bet the community highly appreciates your efforts in doing thorough tests. But if this results in waiting months for using the plugin, then this sort of renders this plugin useless. 

And see, it is already am month now. People suggest workarounds by hacking the XML files in the jar directly.

And after all, you cannot test everything. Things will break, they always do. It is just a matter of time. Why not give this to the community? If something breaks, one can create an issue or even a pull request with a fix. Problems get solved even faster and the plugin is always up to date. I bet the community will find issues you wouldn't ever dream of :smile: 

So, maybe it is still a valid request?

**Comment by OpherV** [comment]
I thought about this again in light of my delay on #204 and the fact I don't want to hinder people that work and rely on my plugin.

I'm definitely willing to remove until-build, but only if we have tests for at least the basic functionality of the plugin. I haven't done this before but this seems like a good start:
https://www.jetbrains.org/intellij/sdk/docs/basics/testing_plugins.html

I'd be thrilled if anyone wants to get the ball rolling with even getting a single test to work

**Comment by OpherV** [comment]
I had yet another remind that APIs break. I'm closing this.
