### ISSUE TITLE
Not working on 182

### ISSUE THREAD

**Issue by RamezIssac** [OpherV/gitflow4idea#204]
* **I'm submitting a ...**
  - [*] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Not working on version 182
i think this is related to #200 

And Thanks for this wonderful plugin !

**Comment by OpherV** [comment]
Rest assured I have an update pending, just waiting to have some time to test it properly

**Comment by RamezIssac** [comment]
Phew.. Thanks!!
Your plugin is really important that it is an update blocker if it is not
there. :-)

Thanks for the great work.

**Comment by SmetDenis** [comment]
@OpherV Thank you! Your plugin is really awesome =)

**Comment by alexanderglueck** [comment]
A workaround if you want to use it until it is updated is to open the plugin .jar file with WinRAR and to edit the `plugin.xml` file within the `META-INF` directory. 

The plugin file can be found (on Windows) at your profile directory eg. `C:\Users\YourUserHere\.PhpStorm2018.2\config\plugins`

Update the `idea-version` tag as can be seen in #201

**Comment by SmetDenis** [comment]
@alexanderglueck Thanks. It works!

**Comment by ruurd** [comment]
We really could use it right now. Please please pretty please?

**Comment by zenphp** [comment]
Is there any timeline for this update?  Is there anything that we as a community can do to help this along?

**Comment by lppedd** [comment]
Actually it's working via Plugin Repo. I'm on the latest 182 EAP.

**Comment by OpherV** [comment]
@zenphp and everyone - 

I do apologize for the delay! My first baby girl was born and there were complications and so all my priorities shifted. I'll be back in business soon to sort this out

**Comment by zenphp** [comment]
@OpherV 

Understandable.  Congrats and hope things settle down for you soon.

**Comment by vobujs** [comment]
> Actually it's working via Plugin Repo. I'm on the latest 182 EAP.

I can confirm this on macOS 10.13.6 w/ WebStorm 2018.2.3 (Build #WS-182.4323.44) - uninstalled and reinstalled the plugin via the regular plugin manager.

**Comment by jayhartley** [comment]
> uninstalled and reinstalled the plugin via the regular plugin manager.
Did you end up installing the forked project? https://github.com/rieonke/idea-git-flow
That's the only Git Flow plugin that comes up when I try to re-install. Not saying it's a bad thing to use a fork - thanks to @rieonke for putting in the time. Just know your source.

**Comment by vobujs** [comment]
> > uninstalled and reinstalled the plugin via the regular plugin manager.
> 
> Did you end up installing the forked project? https://github.com/rieonke/idea-git-flow
> That's the only Git Flow plugin that comes up when I try to re-install. Not saying it's a bad thing to use a fork - thanks to @rieonke for putting in the time. Just know your source.

arghl urgh - you got the right suspicion, I ended up using the fork. so apologies to the round for not looking thoroughly enough.
wanting @OpherV 's version of course, so waiting for him to find some free time.

**Comment by OpherV** [comment]
Great news everyone! My daughter is now fine, and the long awaited release is out.
Please enjoy release 0.6.6 codenamed Emma :)
