### ISSUE TITLE
PhpStorm incompatible with latest version

### ISSUE THREAD

**Issue by applyACS** [OpherV/gitflow4idea#210]
PhpStorm 2018.3
Build #PS-183.4284.150, built on November 21, 2018

**Comment by webcodist** [comment]
A quick workaround https://github.com/OpherV/gitflow4idea/issues/204#issuecomment-409267457
Replace 182.* with 183.*
![image](https://user-images.githubusercontent.com/6401641/49176407-d8d1c600-f35b-11e8-9824-961a81b14fc8.png)

**Comment by OpherV** [comment]
Note that I haven't yet fully tested 183.* compatibility, so use @webcodist's suggestion with caution

New version is in the works - should be released soon™

**Comment by orphanedrecord** [comment]
Looking forward to soon™ being now (or then) … I will donate via your PayPal link !

Colonel Sandurz: Try here. Stop.
Dark Helmet: What the hell am I looking at? When does this happen in the movie?
Colonel Sandurz: Now. You're looking at now, sir. Everything that happens now, is happening now.
Dark Helmet: What happened to then?
Colonel Sandurz: We passed then.
Dark Helmet: When?
Colonel Sandurz: Just now. We're at now now.
Dark Helmet: Go back to then.
Colonel Sandurz: When?
Dark Helmet: Now.
Colonel Sandurz: Now?
Dark Helmet: Now.
Colonel Sandurz: I can't.
Dark Helmet: Why?
Colonel Sandurz: We missed it.
Dark Helmet: When?
Colonel Sandurz: Just now.
Dark Helmet: When will then be now?
Colonel Sandurz: Soon.
Dark Helmet: How soon?

**Comment by OpherV** [comment]
Fixed in 0.6.7

@orphanedrecord  🤣 

<img src="https://media.giphy.com/media/QGBENK0Y6nF4Y/giphy.gif" />
