### ISSUE TITLE
IntelliJ 2018.3.1 Incompatible with the Intellij version

### ISSUE THREAD

**Issue by akuma8** [OpherV/gitflow4idea#212]
![git flow integration](https://user-images.githubusercontent.com/2613496/50045580-7552d280-0095-11e9-8b12-1b3e89cc6060.PNG)
![idea build](https://user-images.githubusercontent.com/2613496/50045603-ed20fd00-0095-11e9-8e73-c3284d985a91.png)

**Comment by llioss** [comment]
Hi, same discussion on the new version here: 
[PhpStorm incompatible with latest version](https://github.com/OpherV/gitflow4idea/issues/210#issuecomment-442760027)

**Comment by straurob** [comment]
I performed some exploratory smoke tests for 2018.3.1. The plugin is basically working.

**Comment by OpherV** [comment]
dup of #210
