### ISSUE TITLE
Add support for PyCharm 2018.3.2

### ISSUE THREAD

**Issue by mabuelhagag** [OpherV/gitflow4idea#215]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
   - It shows `No Gitflow` even after fore re-initialization `git flow init -f`
   - No other errors shown in version control console.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.7
  - Gitflow version: 0.4.1
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
   PyCharm 2018.3.2 (Community Edition)
   Build #PC-183.4886.43, built on December 18, 2018
   JRE: 1.8.0_152-release-1343-b26 x86_64
   JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
   macOS 10.14.1
  ~~~~

**Comment by OpherV** [comment]
@mabuelhagag It sounds you're using [nvie/gitflow](https://github.com/nvie/gitflow) rather than [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh). The former is dead and hasn't been updated in years. Please upgrade to AVH Gitflow
