### ISSUE TITLE
Gitflow never initialized

### ISSUE THREAD

**Issue by adamlalikos** [OpherV/gitflow4idea#217]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Git flow is not showing as initialized, but from the terminal it is. UI is not picking up the initialization / configuration.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**
1. Initialize Git flow (either from IntelliJ or command line `git flow init -f`
2. Reload IntelliJ
3. IDE still states "No Gitflow"

* **What is the expected behavior?**
To the Git flow menu to start / finish features, releases, bug fixes, etc.

* **Please tell me about your environment:**  
  - Gitflow4idea version: Latest (`0.6.7`)
  - Gitflow version: from terminal: `0.4.1`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2018.3.3 RC (Ultimate Edition)
    Build #IU-183.5153.8, built on December 24, 2018
    JRE: 1.8.0_152-release-1343-b26 x86_64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~

  - MacBook Pro (15-inch, 2016)
  - macOs Mojave, Version: 10.14.2 (18C54)

* **Other information** 
Unfortunately, I cannot find any logs / errors / stack traces, even with running via the command line to see IDE output.

**Comment by OpherV** [comment]
@adamlalikos  It sounds you're using [nvie/gitflow](https://github.com/nvie/gitflow) rather than [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh). The former is dead and hasn't been updated in years. Please upgrade to AVH Gitflow

**Comment by adamlalikos** [comment]
@OpherV I see, I've updated and it's now working. Thanks, and sorry for the issue (>.<)

**Comment by chenop** [comment]
Sorry but what does it mean to use gitflow-avh?
[Installation instructions](https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Windows) just say to install git.
I've tried to upgrade git for latest version and it still does not work.

**Comment by chenop** [comment]
Ok, figure this out:
1. Update to latest GIT
2. Run `git flow init` - use default names or insert your branch name 
3. restart IDE

My problem was that the production default branch name was not exist.
