### ISSUE TITLE
Support for IntelliJ 2019.1

### ISSUE THREAD

**Issue by klaushauschild1984** [OpherV/gitflow4idea#221]
After switching to the new EAP (2019.1) the plugin is not more available. I cant even find it in the Plugins sections of Settings.
Maybe there is just the general support for the new version missing?
I miss the plugin because I am not very handy with git command line.

**Comment by roland-d** [comment]
@klaushauschild1984 I second that. Installing the plugin manually doesn't work either as it reports that it is incompatible.

**Comment by boda2004** [comment]
As a workaround you can try to change the line in META_INF/plugin.xml inside gitflow4idea-0.6.7.jar to
`<idea-version since-build="182.0" until-build="191.*"/>`
Not necessarily it will work for you, YMMV

**Comment by roland-d** [comment]
@boda2004 Thank you, that works.

**Comment by klaushauschild1984** [comment]
Works for me too, but a real fix woud be great.

**Comment by jurgenhaas** [comment]
Confirmed, this workaround does work.

**Comment by pdzugas** [comment]
The problem is I can't seem to find any file named **gitflow4idea** on my Linux Mint 19 although I have WebStorm installed (updated regularly) and this plugin is listed there as well (disabled of course due to incompatibility). Can anyone provide any useful hints as to where is that metafile located?

**Comment by boda2004** [comment]
@pdzugas take a look here: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

**Comment by artemsky** [comment]
Can someone post a compiled `gitflow4idea-0.6.7.jar`?

**Comment by pdzugas** [comment]
@boda2004 Thanks a lot, I didn't realize that nemo is not searching in hidden files by default. I confirm that editing metafile did the trick for me as well!

**Comment by hgoertz82** [comment]
how do u repack the jar file?

**Comment by klaushauschild1984** [comment]
It is just an uncompressed zip file.

**Comment by hgoertz82** [comment]
> It is just an uncompressed zip file.

I know that. But uncompressing, edit and compressing doesn't work.

**Comment by renanwilliam** [comment]
You can use vim editor to edit the files in any compressed text files.
1. Navigate to file location from terminal.
2. Type vim name.jar
3. Select the file you want to change and hit “Enter”
4. Edit the file and press “Esc” and “:wq!” to save and quit.

Source: https://forums.macrumors.com/threads/how-to-modify-a-java-jar-file.1136993/#post-23899780

**Comment by sonnysavage** [comment]
For those who, like me, have trouble locating the `jar` file, here's where I found it on my Windows 10 system:
`~/.PhpStorm2019.1/config/plugins/gitflow4idea/lib/gitflow4idea-0.6.7.jar`
