### ISSUE TITLE
Git flow not working Intellij - No Git Flow

### ISSUE THREAD

**Issue by rjouvet** [OpherV/gitflow4idea#222]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

I am working with Android Studio 3.3.1 (Latest)
I downloaded and installed git-flow from the plugin repository. I have done git-flow init -f and multiple other manipulations (like, reinstall everything, remove git project, checkout again, init git flow before, etc...)
Each time the git-flow shows No Gitflow and I am not able to use it in Android studio...

* **What is the expected behavior?**

I should have the possibility to use the context menu.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.7
  - Gitflow version: 0.4.1
  
  - *Android Studio version*
  ~~~~
  Android Studio 3.3.1
  Build #AI-182.5107.16.33.5264788, built on January 29, 2019
  JRE: 1.8.0_152-release-1248-b01 x86_64
  JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  macOS 10.14.3
  ~~~~

**Comment by daniel-scaleforce** [comment]
Same problem for me but with PHPstorm.

**Comment by rebellius** [comment]
Same problem with intelliJ 183. also if i type git flow init -f

**Comment by Sam-Kruglov** [comment]
Same but I have a work around with a precondition.

Run `git flow version`. If it says 0.4.1 then it means you have the vanilla installed (which is last updated in 2012). You must delete that and install https://github.com/petervanderdoes/gitflow-avh instead. When I did that, all worked

**Comment by OpherV** [comment]
@Sam-Kruglov  is correct. You're using [nvie/gitflow](https://github.com/nvie/gitflow) rather than [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh). The former is dead and hasn't been updated in years. Please upgrade to AVH Gitflow

**Comment by charlie45000** [comment]
I have the same problem, but after having installed gitflow-avh the `git flow version` command still outputs: 
```
Failed to create /user.slice/user-1000.slice/session-2.scope/init.scope control group: Permission denied  
Failed to allocate manager object: Permission denied  
0.4.2-pre
```

Do you know what is the problem?

**Comment by shamanis** [comment]
Still actual problem. Git flow plugin not working - "No Gitflow"
git flow version - 1.8.0 (AVH Edition)
pycharm 2019.1.3
gitflow plugun 0.6.8

"git flow init -f" - does not fix the problem

**Comment by ngmip** [comment]
I think I had the same problem and I solved it.

### The Context
Existing Eclipse project imported as maven ptoject. (gitflow used on Eclipse)
several local branch following standard gitflow patterns present in local repository.
Once the plugin installed in IDEA, 'No Gitflow' was visible on bottom tool bar.

### Attempt 1
Clic on the toolbar and select  'Init Repo'. 
On the "Option for gitflow init window" I left the checkbox "use non-default configuration" unchecked.
Click ok.
=> message "_Initialized gitflow in repo FOO_" however still "No Gitflow" in the toolbar

### Attempt 2
Open terminal and type command `git flow init -f`
=> no error however still "No Gitflow"

### Attempt 3
Clic on the toolbar and select  'Init Repo'. 
On the "Option for gitflow init window" I checked the checkbox "use non-default configuration" and left the field as is.
Clic Ok.
=> Error because "develop" was filled for both "production" and "next release" fields
Filled "master" for production
=> Success ! it works now.

Hope this helps.

**Comment by shamanis** [comment]
Sorry. Problem is solved.
Just update git-flow to version 1.12.3.

**Comment by charlie45000** [comment]
> Sorry. Problem is solved.
> Just update git-flow to version 1.12.3.

I have the latest release of gitflow, clion, and gitflow plugin, and it does not work: the already initialized repo is not recognized by the plugin and if I initialize it using clion, the plugin still displays "no gitflow"...

**Comment by SparkyGreens** [comment]
Also getting the same issue in IntelliJ, have updated to git-flow-avh 1.12.3 and git-flow integration plugin to 0.6.8. Have uninstalled git-flow integration and re-installed. Have done "Init Repo" and "git flow init -f" in every combination I can think of. But the same result - "No Gitflow".

**Comment by ivanpadavan** [comment]
> I think I had the same problem and I solved it.
> 
> ### The Context
> Existing Eclipse project imported as maven ptoject. (gitflow used on Eclipse)
> several local branch following standard gitflow patterns present in local repository.
> Once the plugin installed in IDEA, 'No Gitflow' was visible on bottom tool bar.
> 
> ### Attempt 1
> Clic on the toolbar and select 'Init Repo'.
> On the "Option for gitflow init window" I left the checkbox "use non-default configuration" unchecked.
> Click ok.
> => message "_Initialized gitflow in repo FOO_" however still "No Gitflow" in the toolbar
> 
> ### Attempt 2
> Open terminal and type command `git flow init -f`
> => no error however still "No Gitflow"
> 
> ### Attempt 3
> Clic on the toolbar and select 'Init Repo'.
> On the "Option for gitflow init window" I checked the checkbox "use non-default configuration" and left the field as is.
> Clic Ok.
> => Error because "develop" was filled for both "production" and "next release" fields
> Filled "master" for production
> => Success ! it works now.
> 
> Hope this helps.

It's the only way and the exact order that worked for me to make plugin 0.7.0 work on MacOS with 1.12.3 AVH git flow!

**Comment by Toomy** [comment]
@ivanpadavan: This has also worked for me on fedora 30. How-ever Attempt 3 was not necessary.
Thank you for this.
Regards Markus

**Comment by oldj** [comment]
I have the same problem, here is my solution:

1. Upgrade to [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh).
2. Open the `./.git/config` file and remove all paragraphs like `[gitflow "*"]`.
3. Click on the toolbar and select 'Init Repo', then click OK.

==> It works!

**Comment by pdstn12** [comment]
thanks bro
