### ISSUE TITLE
No Fast-forward option is not working

### ISSUE THREAD

**Issue by MrSquaare** [OpherV/gitflow4idea#225]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
The functionality to add the --no-ff option doesn't work

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Open Settings
3. Check "Do not fast-forward..." in feature category and Apply
4. Open Git repository using gitflow
5. Start new feature
6. Create a file, commit and push it
7. Finish the feature
8. Profit

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.7
  - Gitflow version: 1.11.0 (AVH Edition)
  
  - IntelliJ Help -> about > click copy icon and paste here. (I use CLion but I think the problem is also on IntelliJ and other supported products)
  ~~~~
  CLion 2018.3.4
  Build #CL-183.5429.37, built on January 31, 2019
  Licensed to Guillaume Bonnet
  Subscription is active until September 29, 2019
  For educational use only.
  JRE: 1.8.0_152-release-1343-b26 amd64
  JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  Linux 4.15.0-45-generic
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Can you paste the output of the version control console when you reproduce?

**Comment by MrSquaare** [comment]
~~~~
18:14:21.497: [repository] git -c core.quotepath=false -c log.showSignature=false flow feature start example develop
Switched to a new branch 'feature/example'
18:15:46.665: [repository] git -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -- example.txt
18:15:53.102: [repository] git -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -f -- example.txt
18:15:53.105: [repository] git -c core.quotepath=false -c log.showSignature=false commit -F /tmp/git-commit-msg-.txt --
[feature/example de79327] Example
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 example.txt
18:16:02.088: [repository] git -c core.quotepath=false -c log.showSignature=false flow feature finish --keepremote example
Switched to branch 'develop'
~~~~

Thanks

**Comment by MrSquaare** [comment]
Hello,

Is there any news about this bug?

Thank you

**Comment by MrSquaare** [comment]
Hello,

While waiting for a possible patch, here is how to force the no-ff option even for a single commit:
https://github.com/petervanderdoes/gitflow-avh/issues/140#issuecomment-68016681

**Comment by OpherV** [comment]
@MrSquaare how come you closed the issue?

**Comment by OpherV** [comment]
Version 0.6.9 is now on the Jetbrains Repo
