### ISSUE TITLE
Plugin not working completely on Pycharm 2018.3.5

### ISSUE THREAD

**Issue by EricVS** [OpherV/gitflow4idea#227]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
Plugin installs correct and shows No Gitflow. 
Running 'Init Repo' creates branch and switches to it.
After that 'No Gitflow' still shows and there are no 'git flow' commands available.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

Pycharm Professional 2018.3.5 -> Preferences -> Plugins -> Search for Git Flow and install 'Git Flow Integration'.
Restart IDE
Any repository -> Click on 'No Repo' and select Repo Init.
Fill in branch names if required. 
The plugin will change to the 'develop' branch after creating it.
Plugin still shows 'No Gitflow' and doesn't present actions 

* **What is the expected behavior?**
Plugin should show Gitflow actions as indicated.

* **Please tell me about your environment:**
  - Gitflow4idea version: 0.6.7
  - Gitflow version: 0.4.1
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
  PyCharm 2018.3.5 (Professional Edition) 
  Build #PY-183.5912.18, built on February 26, 2019
  Licensed to Eric Van Steenbergen
  Subscription is active until April 20, 2019
  JRE: 1.8.0_152-release-1343-b28 x86_64
  JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  macOS 10.14.4
 ~~~~

**Comment by OpherV** [comment]
@EricVS  You're using [nvie/gitflow](https://github.com/nvie/gitflow) rather than [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh). The former is dead and hasn't been updated in years. Please upgrade to AVH Gitflow

**Comment by EricVS** [comment]
Thank you for your response. I uninstalled git-flow and installed
git-flow-avh. Working in Pycharm as expected!
Thank you very much for a nice and functional plugin!

Kind regards,

*Eric Van Steenbergen*

*E-mail: vs.eric@gmail.com <vs.eric@gmail.com>*
*Skype: ericvs2014*
*LinkedIn: Eric Van Steenbergen
<http://es.linkedin.com/pub/eric-van-steenbergen/b/8a4/51b>*
