### ISSUE TITLE
no gitflow

### ISSUE THREAD

**Issue by fsyyft** [OpherV/gitflow4idea#233]
if you see 'no gitflow' in the status bar you will need to re-init using git flow init -f

->  I've tried many times, but I still can't make it.

OS：macOS 10.14.4
JDK：1.8.0_202
Golang：2019.1.1
Git Flow Integration：0.6.8

**Comment by dingziqian** [comment]
the same problem on "android studio 3.4" 
OS：macOS 10.12.6
JDK：1.8
Git Flow Integration：0.6.8

**Comment by OpherV** [comment]
Closing this because you haven't followed the submission guideline
