### ISSUE TITLE
New version just hangs doing nothing

### ISSUE THREAD

**Issue by bbakermmc** [OpherV/gitflow4idea#234]
I was able to init fine.

But then starting new hotfix, it just spins.

**Comment by josh-stableprice** [comment]
It looks like there is an issue with this plugin where it will hang asking for HTTP login credentials without providing a way to supply them. Our temporary workaround is to turn off the fetch before each action or alternatively using SSH based git auth where this issue doesn't present

**Comment by OpherV** [comment]
Closing because you haven't followed the issue submission guideline.
