### ISSUE TITLE
Finish feature shows merged into null

### ISSUE THREAD

**Issue by roland-d** [OpherV/gitflow4idea#238]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
When I click on Finish feature it switches to the `develop` branch and performs the merge. The balloon showing the success has the following message:
`18:39	strstr-error-on-product-price-import: The feature branch 'feature/strstr-error-on-product-price-import' was merged into 'null'`

Notice how it says it was merged into null. This is not true because the merge was successful.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open PhpStorm
2. Create a feature branch
3. Make some changes and commit them
4. Click on Finish feature
5. Notice the balloon showing the branch was merged into null

* **What is the expected behavior?**
The balloon showing that the branch was merged into `develop`.

* **What is the motivation / use case for changing the behavior?**
Correct return status
* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.6.8
  - Gitflow version: 1.12.0 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
PhpStorm 2019.1.2 Preview
Build #PS-191.7141.35, built on May 2, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )
None at this point

**Comment by OpherV** [comment]
Sounds like #144 is back... I'm closing this and handling it on that thread
