### ISSUE TITLE
Please add 2019.2 support

### ISSUE THREAD

**Issue by BlackRule** [OpherV/gitflow4idea#241]

**Comment by CasterKKK** [comment]
You can just clone the project and change `untilBuild` to `192.*`. I have just done some update but could not push it as a new branch. Any idea? @OpherV

**Comment by gsolecki** [comment]
I would like to join to the request.

**Comment by r-da** [comment]
Yes please update the plugin

**Comment by artemsky** [comment]
Can't w8

**Comment by r-da** [comment]
If you can't wait (like me) here is a workarund that apparently works:

1. find gitflow4idea-0.6.8.jar
    - for 2019.1 users the path is `$HOME/.PhpStorm2019.1/config/plugins/gitflow4idea/lib/gitflow4idea-0.6.8.jar`.
    - for 2019.2 users the path is `$HOME/.PhpStorm2019.2/config/plugins/gitflow4idea/lib/gitflow4idea-0.6.8.jar`
2. modify the `META-INF/plugin.xml` file inside the jar, changing `until-build="191.*"` to `until-build="192.*"`

Now you can use the plugin under 2019.2 and it seems to work correctly.

To modify the jar you can unpack it and then pack it again or use vi:

1. open the jar with vi
2. find the line `META-INF/plugin.xml`
3. press enter
4. change the until-build as above
5. type `:wq!` and then `:q!`

**Comment by palanza** [comment]
+1

**Comment by jayesh-bhadja** [comment]
Yes please update the plugin

**Comment by diesl** [comment]
See also #200 for the general aspect of this issue

**Comment by OpherV** [comment]
I'm aware of this and a new version will be coming. I haven't had the time yet to sort out and properly test the 2019.2 issues. You're welcome to follow @r-da's suggestion but keep in mind this is untested. Testing is important, you don't want weird intellij bugs messing up your repos.

**Comment by FlashGen** [comment]
Apologies if OT, but any chance of AppCode support at the same time?

**Comment by krotoveugene** [comment]
Hey guys, anyone knows how to install a current version of the plugin on 2019.2 IDEA?

**Comment by r-da** [comment]
1. Download the 0.6.8 release [here](https://github.com/OpherV/gitflow4idea/releases)
2. Apply the changes described [here](https://github.com/OpherV/gitflow4idea/issues/241#issuecomment-515444744)
3. Install it manually into IDEA
4. Remember the caveat by [OpherV](https://github.com/OpherV/gitflow4idea/issues/241#issuecomment-517979585)

**Comment by krotoveugene** [comment]
> 1. Download the 0.6.8 release [here](https://github.com/OpherV/gitflow4idea/releases)
> 2. Apply the changes described [here](https://github.com/OpherV/gitflow4idea/issues/241#issuecomment-515444744)
> 3. Install it manually into IDEA
> 4. Remember the caveat by [OpherV](https://github.com/OpherV/gitflow4idea/issues/241#issuecomment-517979585)

When I try to install the plugin, I've got an error: Fail to load plugin descriptor from file gitflow4idea-0.6.8.jar

**Comment by vrobre** [comment]
Is it know when this might be compatile with 2019.2?
It would be great to have this back.

**Comment by krotoveugene** [comment]
Hey guys, I've just found out a solution that works for me (2019.2 version):
1. Clone project (develop branch)
2. Edit build.gradle file - change param `untilBuild` to `192.*` https://github.com/OpherV/gitflow4idea/blob/513aa67423a9986d454c06debe788f9a55d56c0b/build.gradle#L34 
3. Run in IntelliJ IDEA: Gradle -> Tasks -> build -> jar
4. Install plugin from disk

**Comment by bbakermmc** [comment]
@krotoveugene Can you just post the built jar file, would save people the hassle of getting everything needed to build it.

**Comment by krotoveugene** [comment]
[gitflow4idea-0.6.8.zip](https://github.com/OpherV/gitflow4idea/files/3505802/gitflow4idea-0.6.8.zip)

Rename to gitflow4idea-0.6.8.jar

**Comment by DiesIrae** [comment]
Thanks @krotoveugene! Much appreciated :-)

**Comment by lucacri** [comment]
@krotoveugene thank you so much! Hopefully the PR gets merged soon also!

**Comment by OpherV** [comment]
Btw this PR is superficial and doesn't address the issue of actions running as synchronous execution on EDT, which I'm working to sort out before we have true 2019.2 support

**Comment by OpherV** [comment]
Version 0.6.9 is now on the Jetbrains Repo
