### ISSUE TITLE
Should be able to finish a feature when has files in custom changelists.

### ISSUE THREAD

**Issue by matheusgomes1** [OpherV/gitflow4idea#251]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

When I put files in changelist, I can't finish a current feature.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. ???
3. Profit

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *find in IntelliJ settings plugins*
  - Gitflow version: run in terminal `>git flow version`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2018.1.1 EAP (Community Edition)
    Build #IC-181.4445.4, built on March 29, 2018
    JRE: 1.8.0_152-release-1136-b27 x86_64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Hey please provide more information then reopen. 
I can't understand the issue or attempt to help without a proper description

**Comment by matheusgomes1** [comment]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)


* **What is the current behavior?**

When I put files in changelist, I can't finish a current feature.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Edit an file 
3. Create another changelist.
4. add files in this new chagelist.
5. to try finish current feature.

* **What is the expected behavior?**

When I finish an feature, my files in custom changelist should be ignored, and the flow of git should be done.

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *find in IntelliJ settings plugins*
  - Gitflow version: run in terminal `>git flow version`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2018.1.1 EAP (Community Edition)
    Build #IC-181.4445.4, built on March 29, 2018
    JRE: 1.8.0_152-release-1136-b27 x86_64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~



* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Changelist are an intelliJ feature that git isn't aware of.

This plugin is a GUI facade for git flow, and so a feature branch has no concept of what a changelist is. In any case, even with CLI git flow you can't finish a feature when you have uncommitted changes regardless of changelist.
