### ISSUE TITLE
Status is always shown as No gitflow

### ISSUE THREAD

**Issue by roland-d** [OpherV/gitflow4idea#253]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
On repositories where gitflow is setup, the status bar shows as **No gitflow**. I have tried to re-init the git flow by doing a `git flow init -f` but the result is still the same.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open PhpStorm
2. Install version 0.7.0 (modify the metadata info to get it installed in build 193)
3. Notice in the bottom corner that the status is shown as **No gitflow**
![image](https://user-images.githubusercontent.com/359377/66020991-4a812000-e4e9-11e9-8078-5dc4d3597b84.png)

* **What is the expected behavior?**
That there is the option to perform git flow operations.

* **What is the motivation / use case for changing the behavior?**
It does not work as expected at the moment.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.0
  - Gitflow version: 0.4.1
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
```
    PhpStorm 2019.3 EAP
Build #PS-193.3519.40, built on September 23, 2019
PhpStorm EAP User
Expiration date: October 23, 2019
Runtime version: 11.0.4+10-b480.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false
Non-Bundled Plugins: BashSupport, Gitflow, String Manipulation, com.kalessil.phpStorm.phpInspectionsEA, izhangzhihao.rainbow.brackets, net.seesharpsoft.intellij.plugins.csv
```

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )
Running git flow commands from the command line works.

**Comment by javichaques** [comment]
Hi,

I have the same problem with Android Studio 3.5.1 and MacOS Catalina.

`Android Studio 3.5.1
Build #AI-191.8026.42.35.5900203, built on September 25, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15`

**Comment by gn-jgeerds** [comment]
Please note that there are two different implementations of git-flow. Since you are working under macOS, you probably installed it via `brew`. Is that correct? 

Homebrew Formulae:
- [git-flow](https://formulae.brew.sh/formula/git-flow)
- [git-flow-avh](https://formulae.brew.sh/formula/git-flow-avh)

Latest `git-flow` release is from 2011. It seems to me that `git-flow-avh` is kind of the successor of `git-flow` as it is still actively maintained (and by the way also the default in [Debian](https://packages.debian.org/buster/git-flow))

See also the setup section at [git-flow cheatsheet](https://danielkummer.github.io/git-flow-cheatsheet/#setup)

**Comment by roland-d** [comment]
From what I can tell I have `git-flow` installed as I also have version `0.4.1`.

```
$ brew info git-flow
git-flow: stable 0.4.1 (bottled), HEAD
Extensions to follow Vincent Driessen's branching model
https://github.com/nvie/gitflow
Conflicts with:
  git-flow-avh (because Both install `git-flow` binaries and completions)
/usr/local/Cellar/git-flow/0.4.1 (18 files, 119.2KB) *
  Poured from bottle on 2018-07-12 at 22:50:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-flow.rb
```

Should I install `git-flow-avh` instead?

**Comment by gn-jgeerds** [comment]
@roland-d At least I would try it. I had the same problem because I accidentally installed "git-flow" instead of "git-flow-avh".

You may also need to "git flow init" the repository again.

**Comment by roland-d** [comment]
@gn-jgeerds Thank you for the tip. 

So I did the following:
1. I removed the `git-flow`
2. installed `git-flow-avh`
3. forced the git init with `git flow init -f`
4. Restarted PhpStorm
5. Now I can see the git actions again

The only thing I do see (or rather not) is the gitflow icon:
<img width="113" alt="image" src="https://user-images.githubusercontent.com/359377/67125623-8c061080-f1f5-11e9-8d94-a64c4ebd874d.png">

Notice the empty space before the lock, I have to click there to see this:
<img width="138" alt="image" src="https://user-images.githubusercontent.com/359377/67125653-9f18e080-f1f5-11e9-9c1e-373ec81af82d.png">

Any tips for that? ;)

**Comment by OpherV** [comment]
fyi I'm on vacation until the end of the month - will have a look as soon as I'm back. Sorry for the wait

**Comment by roland-d** [comment]
@OpherV No problem, enjoy it while you can. I am gone myself at the end of the week and be quiet for a while :)

**Comment by javichaques** [comment]
> @gn-jgeerds Thank you for the tip.
> 
> So I did the following:
> 
> 1. I removed the `git-flow`
> 2. installed `git-flow-avh`
> 3. forced the git init with `git flow init -f`
> 4. Restarted PhpStorm
> 5. Now I can see the git actions again
> 
> The only thing I do see (or rather not) is the gitflow icon:
> <img alt="image" width="113" src="https://user-images.githubusercontent.com/359377/67125623-8c061080-f1f5-11e9-8d94-a64c4ebd874d.png">
> 
> Notice the empty space before the lock, I have to click there to see this:
> <img alt="image" width="138" src="https://user-images.githubusercontent.com/359377/67125653-9f18e080-f1f5-11e9-9c1e-373ec81af82d.png">
> 
> Any tips for that? ;)
> 
> Edit: This only seems to happen on projects with multiple git repos (submodules)

I did the same and it's work.
Thank you

**Comment by b4cedev** [comment]
@gn-jgeerds Thank you, too. Switching to git-flow-avh solved the problem for me, too 😊

@OpherV: Hope you had a nice vacation! Perhaps your plugin could check git flow version and show some notice on 0.4.1...

**Comment by littleCancer** [comment]
Please add confirmation dialog after selecting finish feature.
In general after selecting every item that can be selected by accident and can cause trouble.

**Comment by OpherV** [comment]
Should be better now with 0.7.1
I do see @roland-d's issue in some cases but haven't found out the cause yet.
The blank space does disappear once you switch between files in the editor.
I'll probably be able to pinpoint the issue in a later version
