### ISSUE TITLE
Tags are not pushed when finishing release

### ISSUE THREAD

**Issue by PioBeat** [OpherV/gitflow4idea#254]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [x] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
If the release branch is pushed to the repository and merged back into develop and master, the tags are not pushed together. Is this the default behavior?

* **What is the expected behavior?**
I am not sure if this is expected or not implemented.
It is more convenient if the tags were pushed together when finishing a release.

* **What is the motivation / use case for changing the behavior?**
GitLab/GitHub automatically create a release when tags are pushed as well.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.0
  - Gitflow version: 1.11.0 (AVH Edition)
  
  - IntelliJ
  ~~~~
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Licensed to Dominik Grzelak
Subscription is active until xxxxxxx
xxxxxxxx
Runtime version: 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10 amd64
VM: OpenJDK 64-Bit Server VM by Private Build
Linux 4.16.18-041618-generic
GC: PS Scavenge, PS MarkSweep
Memory: 3889M
Cores: 4
Registry: 
Non-Bundled Plugins: Lombook Plugin, Gitflow, mobi.hsz.idea.gitignore, org.asciidoctor.intellij.asciidoc, org.intellij.scala, com.vladsch.idea.multimarkdown
  ~~~~

**Comment by OpherV** [comment]
@PioBeat Are you running with the "push on release" flag set in options? (`-p`)

If so - when you run `git flow release finish -p` from the command line does it push tags like you expect? This plugin is just a GUI for the command line version - so if there's an issue with the command line you should post it on the AVH repo. Closing for now

**Comment by PioBeat** [comment]
Thanks for the help! The flag in the options was unset!
