### ISSUE TITLE
null in notification

### ISSUE THREAD

**Issue by vivekmore** [OpherV/gitflow4idea#257]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
After finishing a feature, the event notification reads "... feature was merged to null ..."

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Create a feature branch
3. Add sample commit
3. Click on Finish Feature 

* **What is the expected behavior?**
Notification message should say develop instead of null

* **What is the motivation / use case for changing the behavior?**
Better event notification 

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *0.7.0*
  - Gitflow version: *1.12.3 (AVH Edition)*

```
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Licensed to Vivek More
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true, ide.tooltip.initialDelay=193
Non-Bundled Plugins: Builder Generator, Lombook Plugin, String Manipulation, VisualVMLauncher, com.denis.zaichenko.angular.2.ws.live.templates, Gitflow, mobi.hsz.idea.gitignore, JRebelPlugin, Karma, de.endrullis.idea.postfixtemplates, com.codota.csp.intellij, com.github.masahirosuzuka.PhoneGapIntelliJPlugin, com.intellij.plugins.html.instantEditing, com.jetbrains.lang.ejs, intellij.prettierJS, MavenRunHelper, org.sonarlint.idea, training, zielu.gittoolbox

```  

* **Other information** 
Keep up the good work!!!

**Comment by OpherV** [comment]
I can't seem to reproduce this. 
![image](https://user-images.githubusercontent.com/3951311/70802246-9e499880-1db9-11ea-89d7-d4c399998fc7.png)

Does this reproduce consistently? If so does it happen on all repos/projects or only specific ones?
