### ISSUE TITLE
idea2019.3 not install

### ISSUE THREAD

**Issue by kouyandong** [OpherV/gitflow4idea#259]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

![image](https://user-images.githubusercontent.com/1124278/69529806-ee4bf100-0fab-11ea-994c-44bfb2481108.png)

* **What is the current behavior?**

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. ???
3. Profit

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7
  - Gitflow version: 1.12.3
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.57, built on November 20, 2019
Licensed to Vladislav Kovalenko
Subscription is active until January 9, 2020
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: GrepConsole, JProfiler, JRebelPlugin, Lombook Plugin, MavenRunHelper, SequenceDiagram, String Manipulation, cn.yiiguxing.plugin.translate, com.alibaba.p3c.smartfox, com.alibabacloud.intellij.toolkit-intellij, com.ccnode.codegenerator.MyBatisCodeHelperPro, com.dubreuia, com.github.novotnyr.gitlab-quickmr-idea-plugin, com.ppolivka.gitlabprojects, com.sjhy.plugin.easycode, de.netnexus.camelcaseplugin, gr.jchrist.gitextender, zielu.gittoolbox
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by webcoderkz** [comment]
Yeah, doesn't work with 2019.3

**Comment by roland-d** [comment]
Have a look at an earlier post: https://github.com/OpherV/gitflow4idea/issues/241#issuecomment-515444744

This explains what you can do until the new release is out.

**Comment by webcoderkz** [comment]
@roland-d latest release is 7.0, that doesn't support 2019.3 yet, so we have to manage it from cli.

**Comment by roland-d** [comment]
@webcoderkz I have 0.7.0 (this is the latest release) running just fine on 2019.3

**Comment by RamallahS** [comment]
> @webcoderkz I have 0.7.0 (this is the latest release) running just fine on 2019.3

doesn't work for me (

**Comment by RamallahS** [comment]
> Have a look at an earlier post: [#241 (comment)](https://github.com/OpherV/gitflow4idea/issues/241#issuecomment-515444744)
> 
> This explains what you can do until the new release is out.

Thanks. It's working!

**Comment by AprilViolet** [comment]
Hello,Thank you very much for your project. do you know whether the project will continue to maintain and support idea2019.3?

**Comment by OpherV** [comment]
New version will be in the jetbrains repo soon

**Comment by rpolasek** [comment]
thank you @opher for your work and support :-)

**Comment by palanza** [comment]
+1

**Comment by tommaineult** [comment]
Thx @OpherV for your support and reactivity ;)

**Comment by halilsafakkilic** [comment]
@OpherV thank you for your support. Is the version released?

**Comment by OpherV** [comment]
@halilsafakkilic not yet, still ironing out a few issues (for example #255, #232, #249) once I'm done and properly test it will be released

**Comment by khusamov** [comment]
Why can't the plugin be found on the marketplace?
![image](https://user-images.githubusercontent.com/4146998/70461782-795bd980-1aca-11ea-8c49-236365953f3a.png)

**Comment by RamallahS** [comment]
> Why can't the plugin be found on the marketplace?

Click on Installed. Maybe this plugin will be there and has been installed earlier.

**Comment by khusamov** [comment]
@RamallahS There is no plugin on both tabs!

**Comment by e-belair** [comment]
@khusamov It does not appear because it's incompatible with the current IDE version. You'll have to wait for the next plugin release

**Comment by OpherV** [comment]
Version 0.7.1 now in the repo

**Comment by e-belair** [comment]
Thank you for your work! This plugin is one of the most important for me!
