### ISSUE TITLE
Support for 2019.3 version

### ISSUE THREAD

**Issue by randikabanura** [OpherV/gitflow4idea#261]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

Not supporting for 2019.3

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open Rubymine 2019.3
2. Error message saying git flow integration does not compatible with current version

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *0.7.0*
  - Gitflow version :1.11.0 (AVH Edition)`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
   RubyMine 2019.3
   Build #RM-193.5233.108, built on November 28, 2019
   Runtime version: 11.0.4+10-b520.11 amd64
   VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )
 ~~~~
  Plugin "Git Flow Integration" is incompatible (target build range is 182.0 to 192.*).
 ~~~~

**Comment by alexanderglueck** [comment]
It has already been reported, check https://github.com/OpherV/gitflow4idea/issues/259
