### ISSUE TITLE
Can't see Git Glow status bar on project load (temp solution in this thread)

### ISSUE THREAD

**Issue by mikadev** [OpherV/gitflow4idea#266]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. There is just some blank space instead of 'gitflow' or icon in the right bottom corner
3. Profit

* **What is the expected behavior?**
Display icon or some text

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *0.7.1*
  - Gitflow version: run in terminal `>git flow version`
  `1.12.3 (AVH Edition)`
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2019.3 (Community Edition)
    Build #IC-193.5233.102, built on November 28, 2019
    Runtime version: 11.0.4+10-b520.11 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Windows 10 10.0
    GC: ParNew, ConcurrentMarkSweep
    Memory: 1961M
    Cores: 8
    Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true
    Non-Bundled Plugins: Gitflow, MavenRunHelper, YAML/Ansible support, com.dubreuia, 
    org.apache.camel
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by awittern** [comment]
First things first: Thx for the new version.
Unfortunately I have the same issue: I can't see or access the Git Flow Plugin (same Git Flow and IDE version).

**Comment by OpherV** [comment]
If you switch between files in the editor, does the status bar widget appear?

**Comment by awittern** [comment]
It does! I haven't noticed that ...
**Thx!** At least I am able now to work with the new IDE version and remove the older one :-)
