### ISSUE TITLE
The gitflow panel is missing

### ISSUE THREAD

**Issue by khusamov** [OpherV/gitflow4idea#268]
Why does the panel often disappear at the bottom right of the editor?

Here's a screenshot. There is no gitflow control panel.
![image](https://user-images.githubusercontent.com/4146998/71071579-f273c480-218d-11ea-81ac-c3b6a5c80088.png)

**Comment by OpherV** [comment]
@khusamov please follow the issue submission guide, otherwise I won't be able to assist you

**Comment by khusamov** [comment]
This is not a defect or feature.
It's only a question

**Comment by AprilViolet** [comment]
@khusamov 
You can view the questions #266.
As if it was the first time you opened it, you can switch to another project and open it again or close it and reopen it to show the panel of the following status bar

**Comment by costalfy** [comment]
check here for the solution https://github.com/OpherV/gitflow4idea/issues/266#issuecomment-565717863

**Comment by khusamov** [comment]
@AprilViolet  @costalfy thanks!
