### ISSUE TITLE
Problems with GitFlow check

### ISSUE THREAD

**Issue by o2-mesmer** [OpherV/gitflow4idea#269]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
  Since recent update (of the plugin, I presume), I periodically have *new tabs appearing at the bottom of the IDE screen*, titled "Unsupported Git Flow Verison" (sic!).
  When I click any of them, I get a dialog with two buttons, one of which is called "no", one of which is a *broken* link to a GitHub resource: (wrong) (https://github.com/OpherV/gitflow4idea/blob/develop/GITFLOW_VERSION.md) instead of (correct) (https://github.com/OpherV/gitflow4idea/blob/develop/GITFLOW_VERISON.MD) (sic!).

  Typos aside, I have two problems with this:
  1.  ```
       $ git flow version
       1.12.3 (AVH Edition)
      ```
      (I'm on windows)
  2. **I can't make these tabs go away**, and new ones just keep appearing, cluttering up the screen. I really like your plugin (thanks for the work!) but I will have to remove it at this rate.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

  I don't know exactly how to reproduce it. The check for git flow version must be incorrect, on one hand. In addition, if you have thought of a way to make the "Unsupported Git Flow Verison" (sic.) go away, then it is broken in my setup. If not, clearly you need one.

* **Please tell me about your environment:**
  - Gitflow4idea version: `0.7.1`
  - Gitflow version: `1.12.3 (AVH Edition)`
  
  - ~~~~
    IntelliJ IDEA 2019.2.4 (Ultimate Edition)
    Build #IU-192.7142.36, built on October 29, 2019
    Runtime version: 11.0.4+10-b304.77 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Windows 10 10.0
    ~~~~



* **Other information**
Puppies in pictures are not moving. Ergo, they must be dead. I don't mean to sound pusillanimous, but I find dead puppies a bit gross.

**Comment by OpherV** [comment]
Oh that is definitely not good! Thanks for reporting!
Just fixed the typo.

I've tested the plugin on both my mac and windows machines, so I don't think it's a windows-specific thing (because the version check does work for me). I do wonder why it opens so many tabs for you. The check should only happen once at most in any case, which makes the fact that it happens more very strange. Can you please post a screenshot of that please? I want to see what types of tabs are those.

My thought is maybe you have a custom terminal command defined for idea?

**Comment by o2-mesmer** [comment]
Here you go, hope it helps:
![Capture](https://user-images.githubusercontent.com/56265875/71092316-48089b00-21a7-11ea-9cce-263b973fbd06.PNG)
It is a *modal* dialog by the way.

As for a custom terminal command... perhaps. In Settings -> Tools -> Terminal, I have defined my shell path as `bash.exe`, pointing to a Debian subsystem I have on the box. That being said, git is *also* installed on the subsystem (version `1.12.0 (AVH Edition)`).

**Comment by o2-mesmer** [comment]
I've looked at what your `GitflowVersionTester` does. 
It looks to be a tokenization issue.

```
$ bash.exe -c git flow version
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
<snip />
```
```
$ bash.exe -c "git flow version"
1.12.0 (AVH Edition)
```
Bloody Windoze.

**Comment by OpherV** [comment]
Ok - can you test for me if this still happens if the shell isn't bash? just to pinpoint the issue

Also is the Debian subsystem you're referring to is the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)? What do I need to configure to get the same env as you?

If the bug is indeed in the Idea tokenizer , my thought is to add an option to the settings to skip version checking. That is unless you feel like implementing a check to use a different tokenizer for bash on windows... that would be nicer, better alternative :)

**Comment by o2-mesmer** [comment]
I can remove the bash, but how do I trigger the GitFlow check?

Yes, I'm referring to WSL. AFAICT, following the instructions on [the page](https://docs.microsoft.com/en-us/windows/wsl/install-win10), installing a Debian distro from the store and configuring the "Terminal" plugin in IntelliJ as follows should reproduce the environment.
![Capture](https://user-images.githubusercontent.com/56265875/71096113-0e875e00-21ae-11ea-8211-c0bb67b7c371.PNG)

As for the tokenizer, perhaps doing `commandLine.setExePath("git flow version");` instead of passing the tokens separately would work. But that might also break other setups, so I'm not sure.

But more generally, I wonder about the pertinence of checking the Git installation via the Terminal config. When IntelliJ fires Git commands, it doesn't go through the terminal, AFAICT. Instead, it's configured on its own (and in my case, points to a Git installed on the Windows env). Wouldn't it be possible to perform the check using the Git that's configured there? That might be more correct overall.

**Comment by OpherV** [comment]
The test should be performed once when the plugin is loaded (on project load).

You make a good point, actually. I originally wanted something super contained and simple, to avoid having to go through the Git Flow Actions mechanism but your case demonstrates that it's not as trivial as I imagined. I'll be sure to examine that for next version. Beats having to write a tokenizer that's for sure.

For the time being, I can suggest you build your own version with the check disabled, avoid using the bash shell or use an earlier version of the plugin with the corresponding idea version. I know non of these solutions are ideal but that's what advice I can offer until I have time to resolve this for the new version

**Comment by o2-mesmer** [comment]
All right. Can you quickly tell me (or point me to a resource) how to build and install my own version of the plugin?

**Comment by OpherV** [comment]
Here you go:
https://github.com/OpherV/gitflow4idea/blob/develop/docs/project_setup.md

**Comment by o2-mesmer** [comment]
I can't push a branch onto your repo, so here's a patch:
[Reworked_Gitflow_version_testing.zip](https://github.com/OpherV/gitflow4idea/files/3979340/Reworked_Gitflow_version_testing.zip)

**Comment by OpherV** [comment]
Can you please do this as a pull request against the develop branch?

**Comment by o2-mesmer** [comment]
Right. [Here you go](https://github.com/OpherV/gitflow4idea/pull/270)
