### ISSUE TITLE
Repo is not initialized

### ISSUE THREAD

**Issue by lsvt-andreiy** [OpherV/gitflow4idea#271]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. There is the "No Gitflow"  in the widget at the bottom right.
3. Click on it and select "Init Repo".
4. The popup "Options for gitflow init" opened.
5. Click "OK" button in the popup.
6. "Initializing Repo" is shown in Status bar in the bottom
7. "Initialized gitflow in repo XXXX" status msg is shown
8. No "Gitflow Actions" available. Just have the same again in the bottom right "No Gitflow"

* **What is the expected behavior?**
Should appear Gitflow Actions when click to the widget.

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.1
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1955M
Cores: 8
Registry: 
Non-Bundled Plugins: Gitflow, Quick Notes
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Please try this:
Open the ./.git/config file and remove all paragraphs with [gitflow "*"].
Click on the toolbar and select 'Init Repo', then click OK.

**Comment by lsvt-andreiy** [comment]
Yeah, that worked! Thanks :) Enjoy your coffee! ;)

**Comment by OpherV** [comment]
Glad it worked! Thanks :)
