### ISSUE TITLE
Does not work with Android Studio 3.6 RC2 (based on IntelliJ 2019.2)

### ISSUE THREAD

**Issue by Kisty** [OpherV/gitflow4idea#277]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Shows many many Unsupported Git Flow Version messages on the bottom (yet the flow integration works)
![as-3 6rc2-gitflow](https://user-images.githubusercontent.com/3243752/74033735-b7805700-49ae-11ea-83e0-9add05d3d41f.png)

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open Android Studio 3.6 RC2
2. Install the plugin
3. Profit

* **What is the expected behavior?**
No error messages

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.1
  - Gitflow version: run in terminal `>git flow version` 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
```
Android Studio 3.6 RC 2
Build #AI-192.7142.36.36.6165589, built on January 28, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: CheckStyle-IDEA, Jenkins Control Plugin, Key Promoter X, String Manipulation, Gitflow, com.squareup.ideaplugin.dagger, eu.inmite.android.plugin.butterknifezelezny, mobi.hsz.idea.gitignore, net.vektah.codeglance, com.squareup.sqldelight, com.crashlytics.tools.androidstudio, com.developerphil.adbidea, com.vladsch.idea.multimarkdown
```

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
That's very strange.. I'll try to get that version of Android Studio to test

**Comment by jakublacko** [comment]
Same issue with PhpStorm 2019.3.
I have git flow AVH version installed, but it says "Unsupported git flow version"
`git flow version` returns "1.12.2 (AVH Edition)"

**Comment by OpherV** [comment]
@jakublacko are you also on windows?

**Comment by jakublacko** [comment]
@OpherV  No, I am using MacOS Catalina

**Comment by OpherV** [comment]
@Kisty  @jakublacko
Is this the same behavior for all projects, or just a specific project?

Also - have you perhaps configured any custom shell for the terminal within IDEA?

**Comment by Kisty** [comment]
I believe it is for all projects. I think it has issues trying to reload when logging back in to the workstation.

I have Powershell 6 (`pwsh.exe`) as the custom shell.

**Comment by OpherV** [comment]
@Kisty Thanks. Can you test if the same happens without a custom shell?
I have a feeling that's where the issue lies

**Comment by Kisty** [comment]
Thanks, @OpherV. I tried with and without the custom shell and although it didn't immediately happen, the error did happen eventually throughout the day. I think it might've been to do with when logging back in from leaving it locked for a while.

**Comment by jakublacko** [comment]
Same for me, if it's fresh after restart, it works perfectly, but after few or even single one logging back, then it throw error as mentioned above.

**Comment by soygabimoreno** [comment]
I have the same problem with Android Studio 3.6 on Ubuntu 18.04.
![Screenshot_20200227_163509](https://user-images.githubusercontent.com/1880789/75459211-53cec580-597f-11ea-9403-5925a30e09a0.png)

**Comment by OpherV** [comment]
Did some refactoring, please test with 0.7.2 and reopen if necessary
