### ISSUE TITLE
Problem with keyboard shorcuts

### ISSUE THREAD

**Issue by joucogi** [OpherV/gitflow4idea#284]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Plugin works fine, but when I add a keyboard shortcut (for example in start feature) the action doesn't work. This is the error

>java.lang.NullPointerException
>	at gitflow.ui.AbstractBranchStartDialog.<init>(AbstractBranchStartDialog.java:46)
>	at gitflow.ui.GitflowStartFeatureDialog.<init>(GitflowStartFeatureDialog.java:12)
>	at gitflow.actions.StartFeatureAction.actionPerformed(StartFeatureAction.java:28)
>       ...

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Create a keyboard shortcut for "Start Feature"
2. Run this Shortcut

* **What is the expected behavior?**
I Expect the same as run VCS > Git > Gitflow > Start Feature

This is for "Start Feature" but this happens in all other related actions like "Finish Feature", "Start Hotfix", ...

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.1
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
  IntelliJ IDEA 2019.3.4 (Ultimate Edition)
  Build #IU-193.6911.18, built on March 17, 2020
  Licensed to IntelliJ IDEA Evaluator
  Runtime version: 11.0.6+8-b520.43 x86_64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Please test with 0.7.2, reopen if necessary
