### ISSUE TITLE
Icon cannot be found in 'AllIcons.Vcs.'

### ISSUE THREAD

**Issue by Spacexplosion** [OpherV/gitflow4idea#286]
* **I'm submitting a ...**
  - [* ] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
IDE Fatal Error dialog containing stack trace.
[stacktrace.txt](https://github.com/OpherV/gitflow4idea/files/4440253/stacktrace.txt)

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Click error notification

* **What is the expected behavior?**
No errors

* **Please tell me about your environment:**

  - Gitflow4idea version: 0.7.1
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. *
  ~~~~
JetBrains Rider 2019.3.4
Build #RD-193.6494.48, built on February 27, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 12
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, show.diff.preview.as.editor.tab=true, ide.borderless.title.product=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, ide.borderless.title.project.path=false, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.require.transaction.for.model.changes=false, vcs.non.modal.commit.toggle.ui=false
Non-Bundled Plugins: BashSupport, Gitflow, hadouken.progress.bar, izhangzhihao.rainbow.brackets
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by fabmars** [comment]
It's obvious GitFlow.TraceFeature has an incomplete icon path in plugin.xml
It's easy to make a PR for that: 
1. clone https://github.com/JetBrains/intellij-community/
2. make a choice between the available options https://github.com/JetBrains/intellij-community/tree/master/platform/icons/src/actions
3. update plugin.xml
4. test
