### ISSUE TITLE
Does not work with  IntelliJ 2020.1

### ISSUE THREAD

**Issue by alapierre** [OpherV/gitflow4idea#289]
Plugin Error: Plugin "Git Flow Integration" is incompatible (until build 193.SNAPSHOT < IU-201.6668.121).

**Comment by CC007** [comment]
Duplicate of issue #276 276

**Comment by alapierre** [comment]
thank you, workaround works, and here is pull request https://github.com/OpherV/gitflow4idea/pull/288
