### ISSUE TITLE
Incompatible with Intellij 2020.1

### ISSUE THREAD

**Issue by VLaboratory** [OpherV/gitflow4idea#292]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
I have updated Intelij to the last version (below) and the plugin is imcopatible.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. See installed plugins

* **What is the expected behavior?**
Well, the plugin should be compatible

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~


IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: org.sonarlint.idea, org.jetbrains.kotlin, BashSupport, Docker, PythonCore
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
Dup of #276
