### ISSUE TITLE
Git Flow not working on phpStorm PhpStorm 2020.1.1 PS-201.7223.96

### ISSUE THREAD

**Issue by diogocnunes** [OpherV/gitflow4idea#299]
* **I'm submitting a ...**
  - [x ] bug report
 
* **What is the current behavior?**

Git Flow doesn't work on PhpStorm 2020.1.1 Build #PS-201.7223.96, built on April 30, 2020

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open phpStorm
2. Message "unsupported Git Flow Version" appears on footer

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *0.7.2*
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
   PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: mobi.hsz.idea.gitignore, com.alayouni.ansiHighlight, com.intellij.ideolog, org.jetbrains.plugins.stylus, Gitflow, me.laria.code.idea_caseconv, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, jballant.CommonJSAutoComplete, ru.adelf.idea.dotenv, vip.guco.stylusassist
  ~~~~

* **Other information** 

I use macOS Catalina 10.15.4 (19E287)

**Comment by OpherV** [comment]
Does this happen after restarting PHPStorm?
Do you have any custom shell defined in the IDEA settings?

**Comment by diogocnunes** [comment]
> Does this happen after restarting PHPStorm?
> Do you have any custom shell defined in the IDEA settings?

Yes... I restarted phpStorm and it continues with this message.
I don't have any custom shell.

**Comment by OpherV** [comment]
Sometimes this happens if you have two versions installed (both the deprecated NVIE and the AVH versions).

Any chance running `git flow version` yields different results from the osx terminal and the IDEA terminal?

**Comment by diogocnunes** [comment]
> Sometimes this happens if you have two versions installed (both the deprecated NVIE and the AVH versions).
> 
> Any chance running `git flow version` yields different results from the osx terminal and the IDEA terminal?

This command below i made inside phpStorm:

![Captura de Tela 2020-05-04 às 18 22 14](https://user-images.githubusercontent.com/13525900/80994197-411bb580-8e34-11ea-9365-9451cb0df142.png)

The plugin was working while i'm phpStorm 2019.x. I upgrade today to 2020.1.1 version (with new git flow plugin version) and this stops...

**Comment by OpherV** [comment]
Can you restart IDEA and paste a screenshot of the git/console window? 
It should look like this:
![image](https://user-images.githubusercontent.com/3951311/80996296-3a973900-8e48-11ea-9f29-fcddb267e87e.png)

**Comment by diogocnunes** [comment]
Console doesn't appears, mas IDEA shows me a error now:

`java.lang.AssertionError: No project file for Project (name=hippo, containerState=ACTIVE, componentStore=/Users/dcnunes/Sites/hippo) 
	at gitflow.GitflowImpl.version(GitflowImpl.java:500)
	at gitflow.GitflowVersionTester.init(GitflowVersionTester.java:66)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:285)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by OpherV** [comment]
Ah, interesting. We're getting somewhere
Does `.idea/misc.xml` exist in your project?

**Comment by diogocnunes** [comment]
> Ah, interesting. We're getting somewhere
> Does `.idea/misc.xml` exist in your project?

There are these files in .idea folder:

.idea dcnunes$ ls -la
total 232
-rw-r--r--   1 dcnunes  staff    548  9 Jan 12:06 $CACHE_FILE$
drwxr-xr-x  14 dcnunes  staff    448  4 Mai 19:10 .
drwxr-xr-x  42 dcnunes  staff   1344  4 Mai 15:19 ..
drwxr-xr-x   4 dcnunes  staff    128  4 Mai 09:23 dataSources
-rw-r--r--   1 dcnunes  staff    909  9 Jan 14:59 dataSources.local.xml
-rw-r--r--   1 dcnunes  staff    469  9 Jan 14:53 dataSources.xml
-rw-r--r--   1 dcnunes  staff    169  9 Jan 12:06 dictionaries
-rw-r--r--   1 dcnunes  staff  12478 29 Abr 15:24 hippo.iml
drwxr-xr-x   3 dcnunes  staff     96  9 Jan 12:06 inspectionProfiles
-rw-r--r--   1 dcnunes  staff    262  9 Jan 12:07 modules.xml
-rw-r--r--   1 dcnunes  staff    403  6 Mar 10:58 php-test-framework.xml
-rw-r--r--   1 dcnunes  staff  12377 29 Abr 15:24 php.xml
-rw-r--r--   1 dcnunes  staff    180  9 Jan 12:07 vcs.xml
-rw-r--r--   1 dcnunes  staff  54329  4 Mai 19:10 workspace.xml

**Comment by diogocnunes** [comment]
This folder, in my project, is not versioned

**Comment by OpherV** [comment]
Here's the problem then - something is wrong with your idea project configuration. `misc.xml` should be there and it isn't
I'm sure that if you test with another project it would work fine.
Perhaps try to create a new project, copy over `misc.xml` and edit it to fit your project?

**Comment by diogocnunes** [comment]
> Here's the problem then - something is wrong with your idea project configuration. `misc.xml` should be there and it isn't
> I'm sure that if you test with another project it would work fine.
> Perhaps try to create a new project, copy over `misc.xml` and edit it to fit your project?

Yeah, it works! Copying a misc.xml from old project to my project, plugin back to work! Thanks!
