### ISSUE TITLE
unsupported git flow version

### ISSUE THREAD

**Issue by qinliang373** [OpherV/gitflow4idea#303]
* **I'm submitting a ...**
  - [ ] bug report

java.lang.AssertionError: No project file for Project (name=sse-loan, containerState=ACTIVE, componentStore=D:\workspace\sse-loan) 
	at gitflow.GitflowImpl.version(GitflowImpl.java:500)
	at gitflow.GitflowVersionTester.init(GitflowVersionTester.java:66)
	at gitflow.ui.GitflowWidget$2.run(GitflowWidget.java:285)
	at java.base/java.lang.Thread.run(Thread.java:834)

  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. ???
3. Profit

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *find in IntelliJ settings plugins*
  - Gitflow version: run in terminal `>git flow version`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2020.1.1 ultimate
    JRE: 1.8.0_152-release-1136-b27 x86_64
    JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
dup of #302
