### ISSUE TITLE
Unsupported Git Flow version

### ISSUE THREAD

**Issue by SKProCH** [OpherV/gitflow4idea#310]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
When i open project i got ![image](https://user-images.githubusercontent.com/29896317/85732329-f4ea4480-b703-11ea-9eb5-4a203bcd2490.png)
However, after any interaction with git (e.g. push or commit), this error disappears and everything starts working fine.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ (Rider in my case)
2. Profit

* **What is the expected behavior?**
Plugin should work from the start of the project

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.3
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - JetBrains Rider 2020.2 EAP 4
Build #RD-202.5792.135, built on June 24, 2020
Rider EAP User
Expiration date: July 24, 2020
Runtime version: 11.0.7+10-b944.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0

**Comment by OpherV** [comment]
Very weird. This this happen on every project?

**Comment by SKProCH** [comment]
> Very weird. This this happen on every project?

Yes, in every my project that has git repo initialized

**Comment by sdk0213** [comment]
me too
"Unsupported git flow version" messagebox show on android studio(OS : window and mac)
in my case, this box is never disappers
then, new messagebox is show next at any moment
Fortunately gitflow fuction is correctly perfect

this is screen capture
![](https://github.com/sdk0213/Android-Develop-Info/blob/master/Bug.png?raw=true)



Sorry, Translation (Korea -> English)

**Comment by kyuzoMX** [comment]
In PhpStorm 2020.2 plugin is now incompatible.

Plugin Error: Plugin "Git Flow Integration" is incompatible (until build 201.SNAPSHOT < PS-202.6397.115).

**Comment by WilliamPeralta** [comment]
any update? i have same problem.

```
> git flow version
1.12.3 (AVH Edition)
 ```

**Comment by tschmidt01** [comment]
Same for me:
```
~ » git flow version
1.12.3 (AVH Edition)
```

**Comment by roox-bezborodovla** [comment]
@OpherV , up)
once again, for IDEA 2020.3 EAP:
Incompatible: requires IDE build 202.* or older

**Comment by OpherV** [comment]
Support for EAP versions is usually delayed, but it'll be available eventually

**Comment by katsenkatorz** [comment]
<img width="381" alt="Capture d’écran 2020-11-02 à 10 36 33" src="https://user-images.githubusercontent.com/5629437/97852748-7166e280-1cf7-11eb-9f3a-b7862b00e03a.png">

I have a same problem on phpstorm `2020.2.3`, with `0.4.1` version git-flow. The problem comes from the plugin?

**Comment by OpherV** [comment]
@katsenkatorz  you need the Git Flow AVH version and not the deprecated NVIE one

**Comment by katsenkatorz** [comment]
@OpherV thx to reply, it's working now.

**Comment by OpherV** [comment]
@SKProCH 0.7.5 is out. Can you test with this version?

**Comment by SKProCH** [comment]
@OpherV seems like all working fine.
