### ISSUE TITLE
2020.2 update compatibility

### ISSUE THREAD

**Issue by driici** [OpherV/gitflow4idea#313]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request

* **What is the current behavior?**
Plugin incompatible with latest (2020.2) PHPStorm - possibly other programs from Idea family.

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.3
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020
Runtime version: 11.0.7+10-b944.20 amd64
  ~~~~

From previous incompatibility issues i was able to modify plugin.xml and set current version. So far I was able to install plugin and it seems to be working correctly.

**Comment by OpherV** [comment]
0.7.4 released now to the jetbrains marketplace
