### ISSUE TITLE
2020.3 update compatibility

### ISSUE THREAD

**Issue by alekseyfilippov** [OpherV/gitflow4idea#315]
* **I'm submitting a ...**
  - [*] feature request

* **What is the current behavior?**
Plugin "Git flow integration" (version 0.7.4) is not compatible with the current version of IDE, because it requires build 202.* or older but the current build is IU-203.5600.34

* **What is the expected behavior?**

Compatibility with version 2020.3 of IntelliJ Idea

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.4
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
    IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
    Build #IU-203.5600.34, built on November 5, 2020
    Runtime version: 11.0.8+10-b1145.3 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  ~~~~

**Comment by wxy8866** [comment]
Please

**Comment by tschmidt01** [comment]
I've created a pull request https://github.com/OpherV/gitflow4idea/pull/316, in the meantime you can can checkout my fork and run `buildPlugin` task.

**Comment by AprilViolet** [comment]
@OpherV Please adapt to IDEA 2020.3, thank you very much!

**Comment by bill-thedbaguy** [comment]
> 
> 
> I've created a pull request #316, in the meantime you can can clone my [fork](https://github.com/tschmidt01/gitflow4idea) and run `buildPlugin` task.

@tschmidt01 I apologize if this is simple, but how do I run the 'buildPlugin' task?

**Comment by tschmidt01** [comment]
> > I've created a pull request #316, in the meantime you can can clone my [fork](https://github.com/tschmidt01/gitflow4idea) and run `buildPlugin` task.
> 
> @tschmidt01 I apologize if this is simple, but how do I run the 'buildPlugin' task?

`./gradlew buildPlugin`

**Comment by JayeshB92** [comment]
@OpherV Can we get plugin supported quickly please..?

**Comment by OpherV** [comment]
0.7.5 is out now in the JetBrains repo with 2020.3 support
