### ISSUE TITLE
[BUG] Unsupported Git Flow Version with 1.12.3 (AVH Edition) installed

### ISSUE THREAD

**Issue by CC007** [OpherV/gitflow4idea#323]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
In the status bar tray where you can normally interact with the git flow plugin I now see `Unsupported Git Flow Version`. Clicking it and the button in the pop-up leads me to a website that tells me that I should check if I have Git Flow AVH Edition installed.

The thing is that I do have this installed and it is accessible from CMD, Powershell, Git Bash and even WSL2 Bash.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Click the `Unsupported Git Flow Version Button` in the status bar tray
3. Get this pop-up:
![afbeelding](https://user-images.githubusercontent.com/5381337/109064023-29c2f700-76ea-11eb-881a-fd517856b2b1.png)

* **What is the expected behavior?**
I would expect to get a normal `Gitflow` button in the status bar tray, where I can use Gitflow functionality

* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.5
  - Gitflow version (CMD, Powershell, Git-Bash): 1.12.3
  - Gitflow version (WSL2 Bash): not installed when first encountered. Now 1.11.0
  
  - IntelliJ 
```
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to Rik Schaaf
You have a perpetual fallback license for this version.
Subscription is active until May 2, 2022.
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 24
Registry: terminal.buffer.max.lines.count=10000, compiler.automake.allow.when.app.running=true, tomcat.root.context.by.default=true
Non-Bundled Plugins: com.circleci.intellij, com.nerdscorner.android.plugin.github, io.protostuff.protostuff-jetbrains-plugin, me.laria.code.idea_caseconv, org.toml.lang, com.intellij.kubernetes, String Manipulation, com.euphoricity.gitignore, Gitflow, MavenRunHelper, org.jetbrains.kotlin, zielu.gittoolbox, com.intellij.plugins.html.instantEditing, org.intellij.scala, Pythonid, idea.plugin.protoeditor, com.yoheimuta.intellij.plugin.protolint, ru.meanmail.plugin.requirements, org.rust.lang
```

* **Other information** 
I have used the Gitflow plugin on this PC in the past. I don't know for sure, but it might have broken after an IntelliJ or Gitflow plugin update.

**Comment by osama001** [comment]
Hi 
I was get same problem and I think I solve it

I have windows 10 

I was uninstall git then I install latest version for git
[https://git-scm.com/downloads](https://git-scm.com/downloads)

then in terminal of idea I wrote this
`git flow init -f`
and start new feature and finish it all in commands
after that plugin gitflow4idea work with me with out errors 

I hope this work with U

😊👌

**Comment by CC007** [comment]
For me just initializing the git repo itself was enough (`git init`)

**Comment by jwang0512** [comment]
same problem here.
macOS Big Sur, Idea 2020.3.3, git flow 1.12.3 (AVH Edition)

**Comment by MrCsabaToth** [comment]
Same here.
I'm using PyCharm 2021.1.1
```
$ git flow version
1.12.3 (AVH Edition)
```
And Devuan Linux.

**Comment by OpherV** [comment]
@CC007  @jwang0512 @MrCsabaToth can you share the content of your .git/config file?

**Comment by MrCsabaToth** [comment]
> @CC007 @jwang0512 @MrCsabaToth can you share the content of your .git/config file?

Here is mine: https://pastebin.com/WgttJcBs

**Comment by CC007** [comment]
In my case it happens mostly on projects that don't use git.
I only see it on git projects while IntelliJ is still busy loading the project.

My git config is as follows:
```
user.name=CC007
user.email=<valid email address>
filter.lfs.clean=git lfs clean %f
filter.lfs.smudge=git lfs smudge %f
filter.lfs.required=true
core.autocrlf=true
core.excludesfile=D:\Local\My Documents\gitignore_global.txt
difftool.sourcetree.cmd='' "$LOCAL" "$REMOTE"
mergetool.sourcetree.cmd=''
mergetool.sourcetree.trustexitcode=true
credential.helper=store
```

**Comment by OpherV** [comment]
I committed something to 0.7.7 which is now out that might solve this issue. I'll reopen if it crops up again.
