### ISSUE TITLE
Plugin Incompatible - DataGrip 2021.1

### ISSUE THREAD

**Issue by sercheo87** [OpherV/gitflow4idea#324]
* **I'm submitting a ...**
  - [* ] bug report
  - [x] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
Data Grip was updated to version 2021.1 and the plugin is incompatible and was automatically disabled.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Update DataGrip v2021.1
2. See message inconpatibility

* **What is the expected behavior?**
Enable plugin for use.

* **What is the motivation / use case for changing the behavior?**
N/A

* **Please tell me about your environment:**
  
  - Gitflow4idea version: Git Flow Integration 0.7.5
  - Gitflow version: run in terminal 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
DataGrip 2021.1
Build #DB-211.6693.68, built on March 31, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2032M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: GrepConsole (11.7.211.6085.0), String Manipulation (8.13.203.000.0), com.chrisrm.idea.MaterialThemeUI (6.2.1), com.intellij.tasks (211.6693.44), com.mallowigi (36.0), net.seesharpsoft.intellij.plugins.csv (2.15.1), org.asciidoctor.intellij.asciidoc (0.32.29), org.intellij.plugins.markdown (211.6693.44)

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by yosvield** [comment]
In WebStorm 2021.1 and PhpStorm 2021.1 is not compatible either.

**Comment by OpherV** [comment]
Hang tight I plan to release a new version for 2021-1 in a few days

**Comment by OpherV** [comment]
0.7.6 is now out with support for 2021.1 (build 211)
