### ISSUE TITLE
Unsupported Git Flow Version

### ISSUE THREAD

**Issue by mqvortrup** [OpherV/gitflow4idea#328]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

After update to newest IntelliJ version, the git flow plugin reports "Unsupported Git Flow Version"

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Look at message from git flow plugin in lower right corner

* **What is the expected behavior?**

That the git flow plugin accepts the installed version, 1.12.3 (AVH Edition), of git flow.

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  ~~~~
  IntelliJ IDEA 2021.1 (Community Edition)
  Build #IC-211.6693.111, built on April 6, 2021
  Runtime version: 11.0.10+9-b1341.35 amd64
  VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
  Windows 10 10.0
  GC: ParNew, ConcurrentMarkSweep
  Memory: 1969M
  Cores: 8
  Non-Bundled Plugins: Gitflow (0.7.6), org.jetbrains.kotlin (211-1.4.32-release-IJ6693.72)
  Kotlin: 211-1.4.32-release-IJ6693.72
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

Yes, I have a .idea/misc.xml file.

**Comment by xtreemrage** [comment]
Is your project initialized with `git init`? I had the same experience when I didn't run that command.

**Comment by mqvortrup** [comment]
> Is your project initialized with `git init`? I had the same experience when I didn't run that command. Although the message gives you the wrong idea, like something is wrong...

You're right. If the project already has been initialized, then the message is simply "No gitflow".

Curiously enough, **_after_** having opened an already initialized project, **_then_** the error message in the uninitialized project **_also_** changed from "Unsupported Git Flow Version" to "No gitflow".

**Comment by vulkanino** [comment]
I have the same problem, and that happens each time I upgrade IntelliJ. This is annoying. Can we make so that this plugin runs on every IntelliJ version?

**Comment by OpherV** [comment]
The "unsupported gitflow version" issue has nothing to do with the intellij version. It's a separate bug I'm still tracking.

As for your suggestion @vulkanino 
This has been discussed in the past, the answer is no. See explanation here:
https://github.com/OpherV/gitflow4idea/issues/319
https://github.com/OpherV/gitflow4idea/issues/200

**Comment by vulkanino** [comment]
Please provide at lease a "use at your own risk". We're blocked.

**Comment by JayeshB92** [comment]
Same Issue, Please provide updates ASAP.!!

RubyMine 2021.2
Build #RM-212.4746.90, built on July 26, 2021
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 5120M
Cores: 12

**Comment by OpherV** [comment]
@JayeshB92 it's exactly comments like these that make people want to quit maintaining open source projects. You're using free software provided at no cost for you. You're not in any position to demand anything.

A new version will be available soon and is tracked here - #332 . Until then you can just use 2021.1

**Comment by sirko-uhl** [comment]
> Same Issue, Please provide updates ASAP.!!
> ...

such comments are a shame

**Comment by CC007** [comment]
Not all people know or thought of it, but @JayeshB92 it's better to put a thumbsup reaction on the original post, rather than a comment that adds no additional info regarding the issue. That way you prevent clutter and it gives a nice way for the dev to see how many people experience the same issue, without manually counting all the "same here" comments.

**Comment by OpherV** [comment]
I committed something to 0.7.7 which is now out that might solve this issue. I'll reopen if it crops up again.
