### ISSUE TITLE
Unsupported Git Flow Version for 1.12.3 (AVH Edition)

### ISSUE THREAD

**Issue by amadain17** [OpherV/gitflow4idea#329]
On Idea 2021.1.1 with the Git Flow Integration plugin version 0.7.6 installed I see "Unsupported Git Flow Version" in Idea. My Git Flow version is 1.12.3 (AVH Edition). When I click on the "Unsupported Git Flow Version" message I get a dialog saying "The Git Flow  version isn't supported by the Git Flow Integration plugin" and a link to a page saying that I need the Git Flow AVH edition installed (which I have)

**Comment by autyan** [comment]
same problem.

**Comment by Skitch90** [comment]
Same for me

**Comment by OpherV** [comment]
Does it happen for all projects? Is git flow already initialized in the project? (`git flow init` from cmd)

**Comment by MvdWeetering** [comment]
Same for me

**Comment by amadain17** [comment]
git flow init from command does nothing except I can run the gir flow flow successfully from the command line. The project in idea still shows unsupported git flow

**Comment by RobertoCesar** [comment]
For me, the git flow init command in the project worked, but I had to restart IDEA.

**Comment by CC007** [comment]
Prob related with https://github.com/OpherV/gitflow4idea/issues/323

**Comment by denglele525** [comment]
Before I pulled the project from the GIt repository, I was really confused because of this problem. But then, after pulling one project from the gIt repository, the problem was solved. I think this is a display bug.

**Comment by OpherV** [comment]
I committed something to 0.7.7 which is now out that might solve this issue. I'll reopen if it crops up again.
