### ISSUE TITLE
Phpstorm hangs while changing active tab

### ISSUE THREAD

**Issue by hiredgun** [OpherV/gitflow4idea#33]
I had a problem with my PhpStorm on MAC related with git flow plugin. Every time after changing active tab, PhpStorm hung for about 3 seconds. I wrote about this issue to IntelliJ support and they suggested to turn off Git Flow Integration plugin and it solved my problem.

**Comment by mbence** [comment]
Same issue on Mac with PhpStorm 8.0.2 and plugin v0.4. With or w/o initialized gitflow. Disabling the plugin solves the problem tho.

**Comment by hamedmohammadi** [comment]
same for me on php storm 8.3 and phpstorm 9 on ubuntu 14.04

it will accured when i use severam ALT+~ or ALR + tab a lot 
even when i change my workspace a lot some time it will recovered with 'ibus restart ' but some times i have to kill all process of java 'ps aux|grep java|awk '{print $2}'|xargs kill -9'
