### ISSUE TITLE
2021.2 Compatibility 

### ISSUE THREAD

**Issue by sercheo87** [OpherV/gitflow4idea#332]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**

Plugin is disabled by incompatibility with new version.

**Incompatible: requires IDE build 211.* or older**

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Update DataGrip v2021.2
2. Install plugin *gitflow4idea*
3. Plugin disabled

* **What is the expected behavior?**

PLugin enabled.

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
  
  - Gitflow4idea version: *0.7.6*
  - Gitflow version: `1.12.3 (AVH Edition)`
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  
  ~~~~
  DataGrip 2021.2
  Build #DB-212.4746.86, built on July 26, 2021
  Runtime version: 11.0.11+9-b1504.13 amd64
  VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  GC: G1 Young Generation, G1 Old Generation
  Cores: 8
  Registry: ide.experimental.ui.toolwindow.stripes=true, ide.balloon.shadow.size=0
  Non-Bundled Plugins: GrepConsole (11.10.211.6086.0), String Manipulation (8.15.203.000.3), com.chrisrm.idea.MaterialThemeUI 
  (6.7.2-2021.2), com.intellij.tasks (212.4746.57), com.mallowigi (38.0.0), net.seesharpsoft.intellij.plugins.csv (2.17.1), 
  org.asciidoctor.intellij.asciidoc (0.33.6), org.intellij.plugins.markdown (212.4746.58)
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by OpherV** [comment]
A new version is in the works. Stay tuned!

**Comment by CC007** [comment]
Would it be possible to prepare the plugin on the EAP version in the future, so that it is ready by the time that the next IntelliJ releases properly?

**Comment by code2prog** [comment]
Any news? :)

**Comment by desmond27** [comment]
Until this gets released I just open the terminal in IDEA and use the commands from here - https://danielkummer.github.io/git-flow-cheatsheet/

**Comment by code2prog** [comment]
> Until this gets released I just open the terminal in IDEA and use the commands from here - https://danielkummer.github.io/git-flow-cheatsheet/

I don't see a problem with using a terminal, but you know how it is when you are used to something

**Comment by OpherV** [comment]
Version 0.7.7 with support for 2021.2 is now available in the Jetbrains marketplace
