### ISSUE TITLE
After updating WebStorm to version 2021.2, the plugin broke

### ISSUE THREAD

**Issue by LDWork** [OpherV/gitflow4idea#334]
After updating WebStorm to version 2021.2, the plugin broke

`Plugin 'Git Flow Integration' (version '0.7.6') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is WS-212.4746.80`

**Comment by desmond27** [comment]
Also does not work with IDEA 2021.2

`Plugin 'Git Flow Integration' (version '0.7.6') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is IU-212.4746.92`

**Comment by OpherV** [comment]
Duplicate of #332
