### ISSUE TITLE
Null Pointer when finishing branch: "branch was merged into null"

### ISSUE THREAD

**Issue by van-adam** [OpherV/gitflow4idea#338]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] puppy => You're not submitting a puppy. I already have one and he's [adorable](https://twitter.com/Opherv/status/974341249099542528)

* **What is the current behavior?**
I was working on a bugfix branch that was started from develop branch (also happens with feature branches etc.) and then finished the bugfix branch. The plugin shows following notification: "The bugfix branch 'bugfix/branchName' was merged into 'null' ". Unfortunately, I cannot upload a screenshot for some reason.

* **Is this a bug? Sorry about that. If so give me explicit details how to reproduce:**

1. Open IntelliJ
2. Start Bugfix, Release, or Feature branch
3. Make a commit
4. Finish said branch
5. Read notification

* **What is the expected behavior?**
When finishing a branch, a notification shows "The branchType branch 'branchType/branchName' was merged into 'startBranch'"

* **What is the motivation / use case for changing the behavior?**
it's a bug
* **Please tell me about your environment:**
  
  - Gitflow4idea version: 0.7.7
  - Gitflow version: 1.12.3 (AVH Edition)
  
  - *IntelliJ Help -> about > click copy icon and paste here. Should look like this:*
  ~~~~
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
  ~~~~

* **Other information** (e.g. detailed explanation, stacktrace, related issues, suggestions how to fix, links for me to have context words of praises, pictures of puppies (again with the puppy??) )

**Comment by homburgs** [comment]
there is already a pull request for that reason
#343
