### ISSUE TITLE
multiple repo management not working

### ISSUE THREAD

**Issue by nhp** [OpherV/gitflow4idea#42]
I have a setup like this: 
-root-repo
--extension1-repo
--extension2-repo
The extensions are no submodules but multiple 3rd party addons.
I have enabled the vcs-root directories in phpstorm and i get another gitflow-dropdown in the status bar. The problem is, that all dropdowns only affect my root-repo and i am not able to use git-flow from phpstorm in the sub-repositories.

**Comment by stijniskoning** [comment]
Hello there,

I'm curious about the status for this issue. I'm using multi repo's alot and it would be great to have git flow integration for it.

Kind regards,

Stijn

**Comment by twidi** [comment]
related to #75 ?

**Comment by dkammilla** [comment]
Any updates on this issue?

**Comment by simonberger** [comment]
I am interested in this as well. Stops me from using this great plugin

**Comment by OpherV** [comment]
What a doozy - this took a huge refactor but is finally implemented!
Will be available in the upcoming release

**Comment by OpherV** [comment]
Added in 0.6.1
