### ISSUE TITLE
Implement git flow init -f (force reinit)

### ISSUE THREAD

**Issue by cheipol** [OpherV/gitflow4idea#50]
Once you have init the repository configuration, it's imposible to reconfigure it.

**Comment by OpherV** [comment]
@cheipol Good things come to those who wait (around 5 years 😂)

Now available in 0.7.0 thanks to @bmwsedee's efforts

![image](https://user-images.githubusercontent.com/3951311/64345729-88c61500-cff9-11e9-88e7-b13707a89f7b.png)
