### ISSUE TITLE
Enable custom editing of branch names in non-default configuration

### ISSUE THREAD

**Issue by rbellamy** [OpherV/gitflow4idea#54]
Take a look at a comparison between the plugins init screen and the one from SmartGit/Hg.
![selection_002](https://cloud.githubusercontent.com/assets/94763/4238457/c05ed5d6-39d8-11e4-95da-52d1c209c213.png)

The "next release" and "production release" branches are drop-downs and cannot be edited.

**Comment by VFedyk** [comment]
So what about plans on this feature?

**Comment by OpherV** [comment]
There are definitely plans

**Comment by VFedyk** [comment]
Sounds good. Let's wait another year. ;-)

**Comment by OpherV** [comment]
Or... you can always clone the repo and [give it a go](https://github.com/OpherV/gitflow4idea/blob/develop/docs/project_setup.md) :)

**Comment by VFedyk** [comment]
Yep.) I forgot where is my book "How to learn Java in 21 days". :D

**Comment by OpherV** [comment]
Closing this because I think 5 years waiting for a reply is enough time
