### ISSUE TITLE
Saying that giflow is not installled

### ISSUE THREAD

**Issue by thiswildorchid** [OpherV/gitflow4idea#60]
I know for a fact that I have gitflow installed because I can run it form the command line but in webstorm 9 it is telling me that it is not installed when I try to use the `git flow init` option from the plugin.

you can recreate the issue by 
* Select `git flow init`
* Check `defaults` in the dialog that appears 
* Fill in the appropriate branch details and questions
* Submit form 
* ! Error git flow is not installed

**Comment by OpherV** [comment]
please have a look at #7

**Comment by thiswildorchid** [comment]
@OpherV  thanks. Sorry for the dupe.
