### ISSUE TITLE
Plugin is incompatible with 14.1

### ISSUE THREAD

**Issue by natros** [OpherV/gitflow4idea#61]
git flow version
1.8.0 (AVH Edition)

OSX 10.10.2
Intellij IDEA 14.1 EAP (140.2285.5)

Thanks

**Comment by Phoboss** [comment]
Same problem here with intellij 14.1 released

**Comment by gaurav-** [comment]
It's not working for me either, with IntelliJ 14.1

**Comment by gaurav-** [comment]
@Phoboss it seems to be fixed in the v0.4.2: http://plugins.jetbrains.com/plugin/download?pr=&updateId=19210

**Comment by Phoboss** [comment]
Great! It works now :)
Thanks
