### ISSUE TITLE
Error: Gitflow is not installed

### ISSUE THREAD

**Issue by Leenug** [OpherV/gitflow4idea#7]
When trying to start a new hotfix, feature or release the following error is returned in the event log: 

```
13:18:29 Error: Gitflow is not installed
13:18:29 Error
```

Gitflow is installed and works as expected from both my external terminal and PHP Storms built in terminal.

**Comment by thiswildorchid** [comment]
@plugn it works !

**Comment by sbrowett** [comment]
@plugn - worked for me too on Windows 7 with Cygwin

**Comment by szarouski** [comment]
Following article helped me to get it working on Windows server with msysgit https://github.com/nvie/gitflow/wiki/Windows

**Comment by tonioriol** [comment]
The @plugn solution stopped to work on El Capitan. El Capitan now protects certain system directories in "rootless" mode (a.k.a. System Integrity Protection). If you run these commands you'll see that the directories and files under there are now marked as "restricted. You can disable rootless mode like this:

1. Reboot into recovery mode (reboot and hold down Cmd-R)
2. Open a terminal
3. Use this command: csrutil disable
4. Reboot and run the command that worked prior to El Capitan

When you're done, it is highly recommended that you re-enable SIP by following the same steps, but using csrutil enable in step 3.

**Comment by serdem420** [comment]
`brew install git-flow`
Also works.

**Comment by YixiuJiang** [comment]
Anther update from Mac El capitan. Please refer here [http://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled](url) if you got "operation not permit" issue when try running "sudo ln -s /usr/local/bin/git-flow /usr/bin/git-flow".

**Comment by leomperes** [comment]
+1 for @serdem420

**Comment by ginko** [comment]
Has anyone made this work without changing the root permissions on El Capitan? I reset the symlink to my git and I'm still getting -> "git: 'flow' is not a git command. See 'git --help'.
Did you mean one of these? reflog show"

Both my git and git-flow are in the usr/local/bin directory. Any help is appreciated. Thanks!
➜  ~ which git
/usr/local/bin/git
➜  ~ which git-flow
/usr/local/bin/git-flow

**Comment by roland-d** [comment]
I know this is old but wanted to share my experience on MacOs High Sierra. I solved it by running ```brew install git-flow``` because I installed everything else with brew as well. Thank you for this.

**Comment by flod1** [comment]
i became the same error on windows 10

**Comment by Punksolid** [comment]
On arch linux could be installed through yaourt 

> yaourt -Sy gitflow-avh

**Comment by phelipepalte** [comment]
Solved my problem in MacOS Catalina with `brew install git-flow`

**Comment by 1075551055** [comment]
`brew install git-flow` not work for me,
but `brew install git-flow-avh` works.
[stackoverflow for this issue](https://stackoverflow.com/questions/28437768/git-flow-command-error-flow-is-not-a-git-command)

**Comment by huzefaindxb** [comment]
`brew install git-flow-avh` and then in your project `git flow init` and follow steps to initialize Gitflow. Somehow init Gitflow from plugin doesn't seem to work.
