### ISSUE TITLE
[Bug] Gitflow init with non-default configuration sets wrong prefixes

### ISSUE THREAD

**Issue by pstrnad** [OpherV/gitflow4idea#72]
Start Gitflow init and check "Use non-default configuration". Once the init finishes, open .git/config where you can see:
```
[gitflow "branch"]
	master = master
	develop = develop
[gitflow "prefix"]
	feature = develop
	release = feature/
	hotfix = release/
	support = hotfix/
	versiontag = support/
```
As you can see, the gitflow "prefix" block is generated wrongly - basically, the values are one line down (should be feature = feature/, release = release/, ...)

**Comment by OpherV** [comment]
Hmm probably has to do with 30331b42fdcc2c2f906f95558ae829d821f894e7 - I had a feeling that might break something :)

**Comment by kevintechie** [comment]
I'm seeing the same issue as well. If this can be fixed manually, what value should we use with the versiontag key?

**Comment by riddler2kone** [comment]
In my default configuration file, no value is used with the versiontag key.

**Comment by anoriell** [comment]
I have the same problem. Any news on when it could be fixed? :)
