### ISSUE TITLE
[Bug] "Synchronize" after starting a feature branch while inside another feature branch

### ISSUE THREAD

**Issue by pstrnad** [OpherV/gitflow4idea#73]
When you are in a feature branch A and decide to start another feature branch B (or hotfix, release), this new branch is properly created from "develop", but Idea keeps the files cached. Therefore, in your new branch B you will see all the changes you did in branch A (which are not in develop). If you try to commit, you will also see that these changes from A will be committed as well.

Solution is to click on "Synchronize" button in Idea (Ctrl + Alt + Y) after starting a new branch, which forces Idea to reload all files from the hard drive.
Could you add a similar "Synchronize" call to the plugin?

**Comment by OpherV** [comment]
Do you have this option in Intellij disabled?
![image](https://cloud.githubusercontent.com/assets/3951311/9760429/a5ed2bce-56fd-11e5-8e01-f2d73abdd2ca.png)

**Comment by pstrnad** [comment]
Nope, I have it enabled (checked). Frame activation is when you switch from one tab (file) to another, and it seems that when I do that, the contents are actually synchronized.

However, when I'm working on one file in a feature branch A, commit, then create a new feature branch B (through giflow plugin), the contents are not synchronized. So if I want to work on the same file, I have to remember to manually synchronize, or at least switch to a different file and back. Otherwise, I contaminate my new feature branch with everything that I did in the old branch.

**Comment by OpherV** [comment]
Alright - thanks for the clarification
