### ISSUE TITLE
When I have more than one project I cannot distinguish between them

### ISSUE THREAD

**Issue by natros** [OpherV/gitflow4idea#75]
Hi, 

When I have more than one project I cannot distinguish between them.

![ipb-mybatis_-_candidaturas_-____projects_ipb_candidaturas_](https://cloud.githubusercontent.com/assets/4996289/8327271/fe51a4b0-1a5e-11e5-96aa-414ce21949b4.png)

**Comment by OpherV** [comment]
What does it mean to have more than one project open at the same time? I've never encountered this behavior in IntelliJ

**Comment by natros** [comment]
IntelliJ supports adding several maven projects, just click Add Maven Project.

![chosen_gwt_-_candidaturas_-____projects_ipb_candidaturas_](https://cloud.githubusercontent.com/assets/4996289/8331111/5265844e-1a7e-11e5-9d36-f854930ad8c9.png)

and for easy viewing just select "Group Modules"

![chosen_gwt_-_candidaturas_-____projects_ipb_candidaturas_](https://cloud.githubusercontent.com/assets/4996289/8331140/9492fc52-1a7e-11e5-8ffe-428f986fb545.png)

**Comment by OpherV** [comment]
Unfortunately I don't work with Maven so I have no good way of debugging this.
Do you get extra git widgets on the statusbar as well? Or only gitflow ones?

**Comment by twidi** [comment]
Note that in pycharm you can also have many git sources, so I have the exact same behavior: two `gitflow` entries

**Comment by OpherV** [comment]
This is definitely under the umbrella of tackling the multi-repo issue in #42 
I'm closing to unify all related issues under that issue
