### ISSUE TITLE
Implement authentication password prompt

### ISSUE THREAD

**Issue by Ekusu1** [OpherV/gitflow4idea#77]
When I try to start a feature, hotfix, or release with -F it doesnt work, it just loads forever.

**Comment by OpherV** [comment]
What is the output in the VCS console?

**Comment by Ekusu1** [comment]
`git -c core.quotepath=false flow feature start -F test`
after that the process just keeps running

**Comment by OpherV** [comment]
gitflow4idea is just a wrapper for gitflow... It doesn't handle authentication at all. There are other solutions for auto-authentication for git depending on the OS

**Comment by Ekusu1** [comment]
But it's a plugin for PhpStorm, in my case, and the normal fetch or pull works perfectly fine, so why is it not working with gitflow?

**Comment by OpherV** [comment]
In the meantime if you're running windows I suggest using
https://gitcredentialstore.codeplex.com/

It will force a windows prompt every time git requests credentials

**Comment by Ekusu1** [comment]
I even took a look at git/git (manly because I was borred xD) to see how they handle the authentication but... that didn't help at all. And I also took a look at petervanderdoes/gitflow (that's what im using). specificaly 'git-flow-feature' and Line 201-204

```
# Update the local repo with remote changes, if asked
if flag fetch; then
    git_fetch_branch "$ORIGIN" "$base"
fi
```

as far as I understand it just calls `git fetch origin $base` (don't know what $base is) which works fine ... or not. 
Just tried it with `git fetch origin` in the PhpStorm Terminal and it also asks for authentication.

**Comment by OpherV** [comment]
I'm closing this as I feel this is no longer in the scope of the plugin. If anyone else encounters this issue please post more info here.
