### ISSUE TITLE
Appcode

### ISSUE THREAD

**Issue by plandem** [OpherV/gitflow4idea#86]
Can't install for Appcode - no such plugin at plugin repository

**Comment by OpherV** [comment]
What version of IDEA is your Appcode version based on? (check in about dialog)
Currently gitflow4idea supports until 141, but I'm working on a new one the support the breaking changes introduced in newer versions of IDEA

**Comment by plandem** [comment]
it's Appcode 3.3 EAP. Yes, it's EAP, but i have no any troubles with PhpStorm EAP or IDEA EAP :(

**Comment by OpherV** [comment]
Well luckily for you I've recently gotten into iOS development, so I might be able to look at it soon :)

**Comment by plandem** [comment]
would be cool :)

**Comment by OpherV** [comment]
fixed in version 0.4.5
