### ISSUE TITLE
Allow commit message editing on finishing feature

### ISSUE THREAD

**Issue by benedictleejh** [OpherV/gitflow4idea#89]
It would be nice to be able to edit the commit message on finishing a feature. On the command line, this is automatic, because git flow runs a standard git merge without specifying a commit message, giving you a chance to edit the message. This can be used to describe the feature being merged more, providing a greater understanding of the codebase.

**Comment by OpherV** [comment]
have a look at the discussion on #74 - unfortunately git flow CLI itself doesn't support this. You might want to try and suggest this on the [AVH repo](https://github.com/petervanderdoes/gitflow-avh) - if a day comes and git flow does start to support this I'll be happy to add this to the plugin GUI.
