### ISSUE TITLE
Changing default branch names isn't working

### ISSUE THREAD

**Issue by codingvirtual** [OpherV/gitflow4idea#95]
@OpherV , great plugin - thank you for the work on this! I am new to using the plugin (just installed it today along with the AVH variation of git-flow per your install info). I init'd a repo and changed to a non-standard configuration because I wanted to use a hyphen (-) as the branch separator and not a slash. I'm attaching a screenshot (the 2nd one below) of the VCS console for reference.

I started a new feature named "carriers" and expected I would get a branch named `feature-carriers` and instead it seems to have created `developcarriers` as the branch name (see screenshot below).

Side note: this is with the latest IntelliJ Idea Ultimate version 15 that I just downloaded, though I'm not sure that matters...

![image](https://cloud.githubusercontent.com/assets/5817986/10926637/9d5223ca-825e-11e5-9e1d-924a8eef99c8.png)

![image](https://cloud.githubusercontent.com/assets/5817986/10926570/1a9a34c2-825e-11e5-997b-d836de5a3e40.png)

**Comment by OpherV** [comment]
I just checked and I can confirm an issue with non-standard configuration

How did you try to define a hyphen as a branch separator? I'm not sure that's even possible with git

**Comment by codingvirtual** [comment]
I use a board system called Waffle (www.waffle.io; it's really nice to help organize issues). Due to the way Waffle cross-references issues, the branches need to be named with hyphens. Here's the FAQ: https://github.com/waffleio/waffle.io/wiki/FAQs that talks about the specifics of Gitflow integration. For convenience, here's a screenshot of the specific section:

![image](https://cloud.githubusercontent.com/assets/5817986/10936860/d8279920-82b4-11e5-8c9e-dea318f291ad.png)

In the init dialog, I just edited the default branch names and replaced the trailing slash with a trailing hyphen. Overall, the system is "working" from the point of view that I can start and finish features, they properly merge, etc. It's just the naming that is off.

**Comment by codingvirtual** [comment]
PS: There is a similar plugin for Eclipse that I use and the hyphen does seem to work fine over there. I did not have to install the Gitflow-AVH software for that - apparently they internally coded all the Git stuff. They do require the EGit plugin for Eclipse which provides the Git support right in Eclipse, so my guess is that they are using that rather than going to the OS.

**Comment by pstrnad** [comment]
It's the https://github.com/OpherV/gitflow4idea/issues/72 bug all over again - it's not a problem with the hyphen character.
I have just tried to init gitflow with non-default configuration on version 0.4.6 of the plugin, and the prefixes are wrongly set in the .git/config file again.

Did the fix for that bug get reverted or something?

**Comment by OpherV** [comment]
Fixed in 0.6.1
