### ISSUE TITLE
Maven JGit-Flow Plugin support

### ISSUE THREAD

**Issue by xfh** [OpherV/gitflow4idea#97]
First of all, I really love your plugin. It is super handy!

I have one issue though in some projects, where the Maven JGit-Flow plugin is used. https://bitbucket.org/atlassian/jgit-flow/wiki/Home
The Maven plugin is essentially doing them same as your gitflow4idea plugin, but it also automatically updates project version number (in pom.xml) usign the Maven release plugin in the background. It is in my opinion the best Git Flow option for Maven projects.

However, I really prefer the IDE integration of your plugin and often find myself using gitflow4idea even though I should actually use the Maven JGit-Flow plugin (for instance to update the version number in the  pom.xml files).

It would be great, if gitflow4idea would check whether the current project uses Maven and the JGit-Flow plugin. When it finds the Maven plugin, it could simply forward the actions from the GUI to the Maven implementation, rather than using the native git flow tool.

**Comment by OpherV** [comment]
I don't use Maven myself so I don't have a way to develop or even test that but it doesn't sound too complicated to implement. How about you take a crack at it yourself?

There's a [handy guide](https://github.com/OpherV/gitflow4idea/blob/develop/docs/project_setup.md) on how to build and develop gitflow4idea which should get you up and running in less than 10 minutes.

From there it's just a matter of checking whether the Maven plugin exists and forwarding the actions as you say. It would also be nice for this to be an option in the plugin settings (only if the Maven plugin is in use), which shouldn't take too long either. You can work from example using the existing codebase

**Comment by OpherV** [comment]
Closing as out of scope
