### ISSUE TITLE
Plugin always notifies about update

### ISSUE THREAD

**Issue by jmartsch** [OpherV/gitflow4idea#98]
I got version 0.4.4 for PHPStorm 9 installed. Every time I open my IDE I see the message to update the gitflow plugin. But 0.4.5 is incompatible with this build, and so I can´t update. How can I suppress the notification or update the plugin?

**Comment by OpherV** [comment]
I just sorted this out in the Jetbrains repo. I hope next time your IDE updates its repo listing the message will stop appearing
