### ISSUE TITLE
Pushing finished features/hotfixes to origin

### ISSUE THREAD

**Issue by jurgenhaas** [OpherV/gitflow4idea#99]
Maybe I'm missing something, but if I finish a feature or hotfix, the master doesn't seem to be pushed to origin. Is that by design?

If so, would you mind to implement an option that allowed to push --all origin?

**Comment by OpherV** [comment]
I didn't see such an option in the [git flow wiki](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-git-flow-release). How would you perform this via command line in git flow?

**Comment by OpherV** [comment]
This is already available for releases and hotfixes

![image](https://cloud.githubusercontent.com/assets/3951311/11428770/e2177944-9477-11e5-8c64-5e8fd83f991e.png)


I don't think git flow AVH edition supports pushing develop on finish feature, at least from the [wiki](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-git-flow-feature). If it ever implements that I'll be sure to integrate the feature into the gui

**Comment by jurgenhaas** [comment]
Thanks @OpherV for your feedback. I confused myself as I had set those settings before but didn't realize that they are on a per-project-basis - I expected them to be global.

It's OK as it is now. Thanks for this great plugin.
